module

public import Sarkozy.Odd437MomentChunks.Chunk003

@[expose] public section
set_option backward.privateInPublic true

/-!
# Certified real-power moment of the complete (19,23) width histogram

Generated by `scripts/generate-odd437-moments.py` from the pinned source
`research-notes/next-push/q437-unequal32s.json`, SHA256
`3ef1e78e59f6e90327bd739c8c114604a352bb4ae7f0faecc6d547b3cd0104bc`.

The 3,337 distinct widths cover all 3,645 points. Each block
checks its initial scalings, endpoint powers, integer Taylor comparison and exact
weighted sum inside Lean's kernel. This module adds those proved bounds.
Correspondence to the geometric rows and edge ordering are proved separately.
-/

namespace Sarkozy.Odd437

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

private noncomputable def momentBlocks : List MomentBlock := [
  (MomentChunk000.histogram, 124691546997070103668988456),
  (MomentChunk001.histogram, 90653537962884987725940994),
  (MomentChunk002.histogram, 92456748678260841242167502),
  (MomentChunk003.histogram, 89277755473434004020606768),
  (MomentChunk004.histogram, 98862718942633664467950960),
  (MomentChunk005.histogram, 84370608119942935719495525),
  (MomentChunk006.histogram, 82680231747857464210874046),
  (MomentChunk007.histogram, 93472935226587891544755526),
  (MomentChunk008.histogram, 88753599163831995520305264),
  (MomentChunk009.histogram, 94270069813978122636121938),
  (MomentChunk010.histogram, 89462294028896075619700804),
  (MomentChunk011.histogram, 90609205064437859670675837),
  (MomentChunk012.histogram, 84861158811945303760993180),
  (MomentChunk013.histogram, 91016756734206560965573015),
  (MomentChunk014.histogram, 91511656281687701024341360),
  (MomentChunk015.histogram, 89375243119136483204213718),
  (MomentChunk016.histogram, 94402860106257019092654371),
  (MomentChunk017.histogram, 103802766399383229890428853),
  (MomentChunk018.histogram, 93400642152834967074768417),
  (MomentChunk019.histogram, 87729017032658896549560682),
  (MomentChunk020.histogram, 96800309821810191351452966),
  (MomentChunk021.histogram, 89093513848650799276404592),
  (MomentChunk022.histogram, 101742366597625927572207767),
  (MomentChunk023.histogram, 90860687027154089562052540),
  (MomentChunk024.histogram, 92584932952343307571969548),
  (MomentChunk025.histogram, 97136609260662119238730829),
  (MomentChunk026.histogram, 7252404789868348730600226)]

/-- All 3,337 distinct widths, sorted increasingly, with exact multiplicities. -/
noncomputable def momentHistogram : List (ℕ × ℕ) := momentBlocks.flatMap Prod.fst

private theorem blocks_lower :
    ∀ b ∈ momentBlocks, (b.2 : ℝ) / 1000000000000000000000000 ≤
      (b.1.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (681150585658841330427119 / 10000000000000000000000000 : ℝ))).sum := by
  simp only [momentBlocks, List.forall_mem_cons]
  exact ⟨MomentChunk000.lower_bound,
    MomentChunk001.lower_bound,
    MomentChunk002.lower_bound,
    MomentChunk003.lower_bound,
    MomentChunk004.lower_bound,
    MomentChunk005.lower_bound,
    MomentChunk006.lower_bound,
    MomentChunk007.lower_bound,
    MomentChunk008.lower_bound,
    MomentChunk009.lower_bound,
    MomentChunk010.lower_bound,
    MomentChunk011.lower_bound,
    MomentChunk012.lower_bound,
    MomentChunk013.lower_bound,
    MomentChunk014.lower_bound,
    MomentChunk015.lower_bound,
    MomentChunk016.lower_bound,
    MomentChunk017.lower_bound,
    MomentChunk018.lower_bound,
    MomentChunk019.lower_bound,
    MomentChunk020.lower_bound,
    MomentChunk021.lower_bound,
    MomentChunk022.lower_bound,
    MomentChunk023.lower_bound,
    MomentChunk024.lower_bound,
    MomentChunk025.lower_bound,
    MomentChunk026.lower_bound, by intro x hx; cases hx⟩

private theorem blocks_lower_sum :
    (momentBlocks.map Prod.snd).sum = 2431132176156040890913535684 := by
  decide +kernel

/-- The actual histogram meets the explicit scalar target moment bound. -/
theorem moment_histogram_lower_bound :
    (2431132176156040890913535684 / 1000000000000000000000000 : ℝ) ≤
      (momentHistogram.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (681150585658841330427119 / 10000000000000000000000000 : ℝ))).sum := by
  have h := moment_blocks_lower momentBlocks blocks_lower
  rw [blocks_lower_sum] at h
  simpa only [momentHistogram, Nat.cast_ofNat] using h

end Sarkozy.Odd437
