module

public import Sarkozy.FastPowerCertificate

@[expose] public section
set_option backward.privateInPublic true

/-!
# Soundness of the exact (19,23) width-moment checker

The separate finite certificates are generated by
`scripts/generate-odd437-moments.py` from
`research-notes/next-push/q437-unequal32s.json`.
Source SHA256: `3ef1e78e59f6e90327bd739c8c114604a352bb4ae7f0faecc6d547b3cd0104bc`.

Decimal arithmetic only proposes lower endpoints. All endpoint power bounds,
Taylor comparisons, initial scalings and weighted sums in those files are checked by
Lean's kernel. Each width is compared through its 4096th root. The
correspondence of this histogram to the packed rows is proved separately; this
file makes no assertion about their edge ordering.
-/

namespace Sarkozy.Odd437

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

/-- The shared certificate row and exact arithmetic checker. -/
abbrev MomentEntry := PowerChecker.MomentEntry
/-- The initial values are fixed by the width and lower numerators. -/
def momentEntry (width multiplicity lower low high : ℕ) : MomentEntry :=
  PowerChecker.MomentEntry.scaled 100000000000000 1000000 width multiplicity lower low high

/-- The finite check includes the link from certificate endpoints to the actual width. -/
def momentEntryCheck (e : MomentEntry) : Bool :=
  decide (e.certificate.a0 = e.width * 100000000000000 ∧
    e.certificate.b0 = e.lower * 1000000) &&
    decide (PowerChecker.EndpointValid 1000000000000000000000000000000 681150585658841330427119 10000000000000000000000000 4095 e.certificate)

/-- Analytic soundness of one checked row of the histogram. -/
theorem moment_entry_lower (e : MomentEntry) (he : momentEntryCheck e = true) :
    (e.lower : ℝ) / 1000000000000000000000000 ≤
      ((e.width : ℝ) / 10000000000000000) ^ (681150585658841330427119 / 10000000000000000000000000 : ℝ) := by
  have hh := Bool.and_eq_true_iff.mp he
  have heq : e.certificate.a0 = e.width * 100000000000000 ∧
      e.certificate.b0 = e.lower * 1000000 := of_decide_eq_true hh.1
  have hc : PowerChecker.EndpointValid 1000000000000000000000000000000 681150585658841330427119 10000000000000000000000000 4095 e.certificate :=
    of_decide_eq_true hh.2
  have h := PowerChecker.endpoint_valid_sound hc
  have ha : (e.certificate.a0 : ℝ) / 1000000000000000000000000000000 =
      (e.width : ℝ) / 10000000000000000 := by
    rw [heq.1]
    push_cast
    ring
  have hb : (e.certificate.b0 : ℝ) / 1000000000000000000000000000000 =
      (e.lower : ℝ) / 1000000000000000000000000 := by
    rw [heq.2]
    push_cast
    ring
  norm_num only [Nat.cast_ofNat, Rat.cast_div, Rat.cast_natCast] at h ⊢
  simpa only [ha, hb] using h

/-- Add checked lower endpoints with their natural-number multiplicities. -/
theorem moment_entries_lower (es : List MomentEntry)
    (he : es.all momentEntryCheck = true) :
    (((es.map (fun e => e.multiplicity * e.lower)).sum : ℕ) : ℝ) / 1000000000000000000000000 ≤
      (es.map (fun e => (e.multiplicity : ℝ) *
        ((e.width : ℝ) / 10000000000000000) ^
          (681150585658841330427119 / 10000000000000000000000000 : ℝ))).sum := by
  induction es with
  | nil => simp
  | cons e es ih =>
    have hh := Bool.and_eq_true_iff.mp he
    have hp := mul_le_mul_of_nonneg_left (moment_entry_lower e hh.1)
      (Nat.cast_nonneg e.multiplicity : (0 : ℝ) ≤ e.multiplicity)
    have ht := ih hh.2
    simp only [List.map_cons, List.sum_cons, Nat.cast_add, Nat.cast_mul, add_div]
    nlinarith

/-- A histogram and its certified lower numerator. -/
abbrev MomentBlock := List (ℕ × ℕ) × ℕ

/-- Add any finite list of independently proved histogram moment bounds. -/
theorem moment_blocks_lower (bs : List MomentBlock)
    (he : ∀ b ∈ bs, (b.2 : ℝ) / 1000000000000000000000000 ≤
      (b.1.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (681150585658841330427119 / 10000000000000000000000000 : ℝ))).sum) :
    (((bs.map Prod.snd).sum : ℕ) : ℝ) / 1000000000000000000000000 ≤
      ((bs.flatMap Prod.fst).map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (681150585658841330427119 / 10000000000000000000000000 : ℝ))).sum := by
  induction bs with
  | nil => simp
  | cons b bs ih =>
    have hb := he b (by simp)
    have ht := ih (fun c hc => he c (by simp [hc]))
    simp only [List.map_cons, List.sum_cons, Nat.cast_add, add_div,
      List.flatMap_cons, List.map_append, List.sum_append]
    exact add_le_add hb ht

end Sarkozy.Odd437
