import Sarkozy.Ranked
import Sarkozy.CRT
import Sarkozy.Examples
import Sarkozy.Target
import Sarkozy.QuantitativeExamples
import Sarkozy.RecordTarget
import Sarkozy.OddData215
import Sarkozy.ActualOddTarget
import Sarkozy.Odd437Threshold
import Sarkozy.OddMoments
import Sarkozy.PowerPolynomial
import Sarkozy.OneOddTarget
import Sarkozy.Odd215Moment
import Sarkozy.FullTarget
import Sarkozy.Odd437Moment
