import Sarkozy.OddOrderChunks215.Chunk25

/-! Generated by `scripts/generate-odd-order-chunks.py`.
Kernel checks for rows 3328 through 3455, inclusive.
The import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder215

open OddOrder

theorem source_chunk_26 :
    allIndexed (sourceCheck 5 43 3 G5 G43 endpointTable) 3328
      ((rows.drop 3328).take 128) = true := by
  decide +kernel

theorem target_chunk_26 :
    allIndexed (fastTargetCheck 4913 5 43 3 G5 G43 endpointTable) 3328
      ((rows.drop 3328).take 128) = true := by
  decide +kernel

end Sarkozy.OddOrder215
