import Sarkozy.OddOrderChunks215.Chunk14

/-! Generated by `scripts/generate-odd-order-chunks.py`.
Kernel checks for rows 1920 through 2047, inclusive.
The import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder215

open OddOrder

theorem source_chunk_15 :
    allIndexed (sourceCheck 5 43 3 G5 G43 endpointTable) 1920
      ((rows.drop 1920).take 128) = true := by
  decide +kernel

theorem target_chunk_15 :
    allIndexed (fastTargetCheck 4913 5 43 3 G5 G43 endpointTable) 1920
      ((rows.drop 1920).take 128) = true := by
  decide +kernel

end Sarkozy.OddOrder215
