import Sarkozy.OddOrderBase437

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 0 through 1023, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_00 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 0
      ((rows.drop 0).take 128) = true := by
  decide +kernel

theorem target_chunk_00 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 0
      ((rows.drop 0).take 128) = true := by
  decide +kernel

theorem source_chunk_01 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 128
      ((rows.drop 128).take 128) = true := by
  decide +kernel

theorem target_chunk_01 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 128
      ((rows.drop 128).take 128) = true := by
  decide +kernel

theorem source_chunk_02 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 256
      ((rows.drop 256).take 128) = true := by
  decide +kernel

theorem target_chunk_02 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 256
      ((rows.drop 256).take 128) = true := by
  decide +kernel

theorem source_chunk_03 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 384
      ((rows.drop 384).take 128) = true := by
  decide +kernel

theorem target_chunk_03 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 384
      ((rows.drop 384).take 128) = true := by
  decide +kernel

theorem source_chunk_04 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 512
      ((rows.drop 512).take 128) = true := by
  decide +kernel

theorem target_chunk_04 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 512
      ((rows.drop 512).take 128) = true := by
  decide +kernel

theorem source_chunk_05 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 640
      ((rows.drop 640).take 128) = true := by
  decide +kernel

theorem target_chunk_05 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 640
      ((rows.drop 640).take 128) = true := by
  decide +kernel

theorem source_chunk_06 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 768
      ((rows.drop 768).take 128) = true := by
  decide +kernel

theorem target_chunk_06 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 768
      ((rows.drop 768).take 128) = true := by
  decide +kernel

theorem source_chunk_07 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 896
      ((rows.drop 896).take 128) = true := by
  decide +kernel

theorem target_chunk_07 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 896
      ((rows.drop 896).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
