import Sarkozy.OddOrderChunks437.Chunk11

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 12288 through 13311, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_96 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12288
      ((rows.drop 12288).take 128) = true := by
  decide +kernel

theorem target_chunk_96 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12288
      ((rows.drop 12288).take 128) = true := by
  decide +kernel

theorem source_chunk_97 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12416
      ((rows.drop 12416).take 128) = true := by
  decide +kernel

theorem target_chunk_97 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12416
      ((rows.drop 12416).take 128) = true := by
  decide +kernel

theorem source_chunk_98 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12544
      ((rows.drop 12544).take 128) = true := by
  decide +kernel

theorem target_chunk_98 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12544
      ((rows.drop 12544).take 128) = true := by
  decide +kernel

theorem source_chunk_99 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12672
      ((rows.drop 12672).take 128) = true := by
  decide +kernel

theorem target_chunk_99 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12672
      ((rows.drop 12672).take 128) = true := by
  decide +kernel

theorem source_chunk_100 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12800
      ((rows.drop 12800).take 128) = true := by
  decide +kernel

theorem target_chunk_100 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12800
      ((rows.drop 12800).take 128) = true := by
  decide +kernel

theorem source_chunk_101 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12928
      ((rows.drop 12928).take 128) = true := by
  decide +kernel

theorem target_chunk_101 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12928
      ((rows.drop 12928).take 128) = true := by
  decide +kernel

theorem source_chunk_102 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13056
      ((rows.drop 13056).take 128) = true := by
  decide +kernel

theorem target_chunk_102 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13056
      ((rows.drop 13056).take 128) = true := by
  decide +kernel

theorem source_chunk_103 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13184
      ((rows.drop 13184).take 128) = true := by
  decide +kernel

theorem target_chunk_103 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13184
      ((rows.drop 13184).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
