import Sarkozy.OddOrderChunks437.Chunk06

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 7168 through 8191, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_56 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7168
      ((rows.drop 7168).take 128) = true := by
  decide +kernel

theorem target_chunk_56 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7168
      ((rows.drop 7168).take 128) = true := by
  decide +kernel

theorem source_chunk_57 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7296
      ((rows.drop 7296).take 128) = true := by
  decide +kernel

theorem target_chunk_57 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7296
      ((rows.drop 7296).take 128) = true := by
  decide +kernel

theorem source_chunk_58 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7424
      ((rows.drop 7424).take 128) = true := by
  decide +kernel

theorem target_chunk_58 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7424
      ((rows.drop 7424).take 128) = true := by
  decide +kernel

theorem source_chunk_59 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7552
      ((rows.drop 7552).take 128) = true := by
  decide +kernel

theorem target_chunk_59 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7552
      ((rows.drop 7552).take 128) = true := by
  decide +kernel

theorem source_chunk_60 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7680
      ((rows.drop 7680).take 128) = true := by
  decide +kernel

theorem target_chunk_60 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7680
      ((rows.drop 7680).take 128) = true := by
  decide +kernel

theorem source_chunk_61 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7808
      ((rows.drop 7808).take 128) = true := by
  decide +kernel

theorem target_chunk_61 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7808
      ((rows.drop 7808).take 128) = true := by
  decide +kernel

theorem source_chunk_62 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7936
      ((rows.drop 7936).take 128) = true := by
  decide +kernel

theorem target_chunk_62 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7936
      ((rows.drop 7936).take 128) = true := by
  decide +kernel

theorem source_chunk_63 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8064
      ((rows.drop 8064).take 128) = true := by
  decide +kernel

theorem target_chunk_63 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8064
      ((rows.drop 8064).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
