import Sarkozy.OddOrderChunks437.Chunk10

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 11264 through 12287, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_88 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11264
      ((rows.drop 11264).take 128) = true := by
  decide +kernel

theorem target_chunk_88 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11264
      ((rows.drop 11264).take 128) = true := by
  decide +kernel

theorem source_chunk_89 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11392
      ((rows.drop 11392).take 128) = true := by
  decide +kernel

theorem target_chunk_89 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11392
      ((rows.drop 11392).take 128) = true := by
  decide +kernel

theorem source_chunk_90 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11520
      ((rows.drop 11520).take 128) = true := by
  decide +kernel

theorem target_chunk_90 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11520
      ((rows.drop 11520).take 128) = true := by
  decide +kernel

theorem source_chunk_91 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11648
      ((rows.drop 11648).take 128) = true := by
  decide +kernel

theorem target_chunk_91 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11648
      ((rows.drop 11648).take 128) = true := by
  decide +kernel

theorem source_chunk_92 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11776
      ((rows.drop 11776).take 128) = true := by
  decide +kernel

theorem target_chunk_92 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11776
      ((rows.drop 11776).take 128) = true := by
  decide +kernel

theorem source_chunk_93 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11904
      ((rows.drop 11904).take 128) = true := by
  decide +kernel

theorem target_chunk_93 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11904
      ((rows.drop 11904).take 128) = true := by
  decide +kernel

theorem source_chunk_94 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12032
      ((rows.drop 12032).take 128) = true := by
  decide +kernel

theorem target_chunk_94 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12032
      ((rows.drop 12032).take 128) = true := by
  decide +kernel

theorem source_chunk_95 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 12160
      ((rows.drop 12160).take 128) = true := by
  decide +kernel

theorem target_chunk_95 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 12160
      ((rows.drop 12160).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
