import Sarkozy.OddOrderChunks437.Chunk17

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 18432 through 19455, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_144 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18432
      ((rows.drop 18432).take 128) = true := by
  decide +kernel

theorem target_chunk_144 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18432
      ((rows.drop 18432).take 128) = true := by
  decide +kernel

theorem source_chunk_145 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18560
      ((rows.drop 18560).take 128) = true := by
  decide +kernel

theorem target_chunk_145 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18560
      ((rows.drop 18560).take 128) = true := by
  decide +kernel

theorem source_chunk_146 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18688
      ((rows.drop 18688).take 128) = true := by
  decide +kernel

theorem target_chunk_146 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18688
      ((rows.drop 18688).take 128) = true := by
  decide +kernel

theorem source_chunk_147 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18816
      ((rows.drop 18816).take 128) = true := by
  decide +kernel

theorem target_chunk_147 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18816
      ((rows.drop 18816).take 128) = true := by
  decide +kernel

theorem source_chunk_148 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18944
      ((rows.drop 18944).take 128) = true := by
  decide +kernel

theorem target_chunk_148 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18944
      ((rows.drop 18944).take 128) = true := by
  decide +kernel

theorem source_chunk_149 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 19072
      ((rows.drop 19072).take 128) = true := by
  decide +kernel

theorem target_chunk_149 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 19072
      ((rows.drop 19072).take 128) = true := by
  decide +kernel

theorem source_chunk_150 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 19200
      ((rows.drop 19200).take 128) = true := by
  decide +kernel

theorem target_chunk_150 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 19200
      ((rows.drop 19200).take 128) = true := by
  decide +kernel

theorem source_chunk_151 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 19328
      ((rows.drop 19328).take 128) = true := by
  decide +kernel

theorem target_chunk_151 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 19328
      ((rows.drop 19328).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
