import Sarkozy.OddOrderChunks437.Chunk15

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 16384 through 17407, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_128 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16384
      ((rows.drop 16384).take 128) = true := by
  decide +kernel

theorem target_chunk_128 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16384
      ((rows.drop 16384).take 128) = true := by
  decide +kernel

theorem source_chunk_129 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16512
      ((rows.drop 16512).take 128) = true := by
  decide +kernel

theorem target_chunk_129 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16512
      ((rows.drop 16512).take 128) = true := by
  decide +kernel

theorem source_chunk_130 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16640
      ((rows.drop 16640).take 128) = true := by
  decide +kernel

theorem target_chunk_130 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16640
      ((rows.drop 16640).take 128) = true := by
  decide +kernel

theorem source_chunk_131 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16768
      ((rows.drop 16768).take 128) = true := by
  decide +kernel

theorem target_chunk_131 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16768
      ((rows.drop 16768).take 128) = true := by
  decide +kernel

theorem source_chunk_132 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16896
      ((rows.drop 16896).take 128) = true := by
  decide +kernel

theorem target_chunk_132 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16896
      ((rows.drop 16896).take 128) = true := by
  decide +kernel

theorem source_chunk_133 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17024
      ((rows.drop 17024).take 128) = true := by
  decide +kernel

theorem target_chunk_133 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17024
      ((rows.drop 17024).take 128) = true := by
  decide +kernel

theorem source_chunk_134 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17152
      ((rows.drop 17152).take 128) = true := by
  decide +kernel

theorem target_chunk_134 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17152
      ((rows.drop 17152).take 128) = true := by
  decide +kernel

theorem source_chunk_135 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17280
      ((rows.drop 17280).take 128) = true := by
  decide +kernel

theorem target_chunk_135 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17280
      ((rows.drop 17280).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
