import Sarkozy.OddOrderChunks437.Chunk04

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 5120 through 6143, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_40 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5120
      ((rows.drop 5120).take 128) = true := by
  decide +kernel

theorem target_chunk_40 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5120
      ((rows.drop 5120).take 128) = true := by
  decide +kernel

theorem source_chunk_41 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5248
      ((rows.drop 5248).take 128) = true := by
  decide +kernel

theorem target_chunk_41 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5248
      ((rows.drop 5248).take 128) = true := by
  decide +kernel

theorem source_chunk_42 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5376
      ((rows.drop 5376).take 128) = true := by
  decide +kernel

theorem target_chunk_42 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5376
      ((rows.drop 5376).take 128) = true := by
  decide +kernel

theorem source_chunk_43 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5504
      ((rows.drop 5504).take 128) = true := by
  decide +kernel

theorem target_chunk_43 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5504
      ((rows.drop 5504).take 128) = true := by
  decide +kernel

theorem source_chunk_44 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5632
      ((rows.drop 5632).take 128) = true := by
  decide +kernel

theorem target_chunk_44 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5632
      ((rows.drop 5632).take 128) = true := by
  decide +kernel

theorem source_chunk_45 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5760
      ((rows.drop 5760).take 128) = true := by
  decide +kernel

theorem target_chunk_45 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5760
      ((rows.drop 5760).take 128) = true := by
  decide +kernel

theorem source_chunk_46 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 5888
      ((rows.drop 5888).take 128) = true := by
  decide +kernel

theorem target_chunk_46 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 5888
      ((rows.drop 5888).take 128) = true := by
  decide +kernel

theorem source_chunk_47 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6016
      ((rows.drop 6016).take 128) = true := by
  decide +kernel

theorem target_chunk_47 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6016
      ((rows.drop 6016).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
