import Sarkozy.OddOrderChunks437.Chunk09

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 10240 through 11263, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_80 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10240
      ((rows.drop 10240).take 128) = true := by
  decide +kernel

theorem target_chunk_80 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10240
      ((rows.drop 10240).take 128) = true := by
  decide +kernel

theorem source_chunk_81 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10368
      ((rows.drop 10368).take 128) = true := by
  decide +kernel

theorem target_chunk_81 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10368
      ((rows.drop 10368).take 128) = true := by
  decide +kernel

theorem source_chunk_82 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10496
      ((rows.drop 10496).take 128) = true := by
  decide +kernel

theorem target_chunk_82 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10496
      ((rows.drop 10496).take 128) = true := by
  decide +kernel

theorem source_chunk_83 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10624
      ((rows.drop 10624).take 128) = true := by
  decide +kernel

theorem target_chunk_83 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10624
      ((rows.drop 10624).take 128) = true := by
  decide +kernel

theorem source_chunk_84 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10752
      ((rows.drop 10752).take 128) = true := by
  decide +kernel

theorem target_chunk_84 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10752
      ((rows.drop 10752).take 128) = true := by
  decide +kernel

theorem source_chunk_85 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10880
      ((rows.drop 10880).take 128) = true := by
  decide +kernel

theorem target_chunk_85 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10880
      ((rows.drop 10880).take 128) = true := by
  decide +kernel

theorem source_chunk_86 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11008
      ((rows.drop 11008).take 128) = true := by
  decide +kernel

theorem target_chunk_86 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11008
      ((rows.drop 11008).take 128) = true := by
  decide +kernel

theorem source_chunk_87 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 11136
      ((rows.drop 11136).take 128) = true := by
  decide +kernel

theorem target_chunk_87 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 11136
      ((rows.drop 11136).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
