import Sarkozy.OddOrderChunks437.Chunk18

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 19456 through 19682, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_152 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 19456
      ((rows.drop 19456).take 128) = true := by
  decide +kernel

theorem target_chunk_152 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 19456
      ((rows.drop 19456).take 128) = true := by
  decide +kernel

theorem source_chunk_153 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 19584
      ((rows.drop 19584).take 128) = true := by
  decide +kernel

theorem target_chunk_153 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 19584
      ((rows.drop 19584).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
