import Sarkozy.OddOrderChunks437.Chunk16

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 17408 through 18431, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_136 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17408
      ((rows.drop 17408).take 128) = true := by
  decide +kernel

theorem target_chunk_136 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17408
      ((rows.drop 17408).take 128) = true := by
  decide +kernel

theorem source_chunk_137 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17536
      ((rows.drop 17536).take 128) = true := by
  decide +kernel

theorem target_chunk_137 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17536
      ((rows.drop 17536).take 128) = true := by
  decide +kernel

theorem source_chunk_138 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17664
      ((rows.drop 17664).take 128) = true := by
  decide +kernel

theorem target_chunk_138 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17664
      ((rows.drop 17664).take 128) = true := by
  decide +kernel

theorem source_chunk_139 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17792
      ((rows.drop 17792).take 128) = true := by
  decide +kernel

theorem target_chunk_139 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17792
      ((rows.drop 17792).take 128) = true := by
  decide +kernel

theorem source_chunk_140 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 17920
      ((rows.drop 17920).take 128) = true := by
  decide +kernel

theorem target_chunk_140 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 17920
      ((rows.drop 17920).take 128) = true := by
  decide +kernel

theorem source_chunk_141 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18048
      ((rows.drop 18048).take 128) = true := by
  decide +kernel

theorem target_chunk_141 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18048
      ((rows.drop 18048).take 128) = true := by
  decide +kernel

theorem source_chunk_142 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18176
      ((rows.drop 18176).take 128) = true := by
  decide +kernel

theorem target_chunk_142 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18176
      ((rows.drop 18176).take 128) = true := by
  decide +kernel

theorem source_chunk_143 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 18304
      ((rows.drop 18304).take 128) = true := by
  decide +kernel

theorem target_chunk_143 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 18304
      ((rows.drop 18304).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
