import Sarkozy.OddOrderChunks437.Chunk01

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 2048 through 3071, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_16 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2048
      ((rows.drop 2048).take 128) = true := by
  decide +kernel

theorem target_chunk_16 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2048
      ((rows.drop 2048).take 128) = true := by
  decide +kernel

theorem source_chunk_17 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2176
      ((rows.drop 2176).take 128) = true := by
  decide +kernel

theorem target_chunk_17 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2176
      ((rows.drop 2176).take 128) = true := by
  decide +kernel

theorem source_chunk_18 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2304
      ((rows.drop 2304).take 128) = true := by
  decide +kernel

theorem target_chunk_18 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2304
      ((rows.drop 2304).take 128) = true := by
  decide +kernel

theorem source_chunk_19 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2432
      ((rows.drop 2432).take 128) = true := by
  decide +kernel

theorem target_chunk_19 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2432
      ((rows.drop 2432).take 128) = true := by
  decide +kernel

theorem source_chunk_20 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2560
      ((rows.drop 2560).take 128) = true := by
  decide +kernel

theorem target_chunk_20 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2560
      ((rows.drop 2560).take 128) = true := by
  decide +kernel

theorem source_chunk_21 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2688
      ((rows.drop 2688).take 128) = true := by
  decide +kernel

theorem target_chunk_21 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2688
      ((rows.drop 2688).take 128) = true := by
  decide +kernel

theorem source_chunk_22 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2816
      ((rows.drop 2816).take 128) = true := by
  decide +kernel

theorem target_chunk_22 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2816
      ((rows.drop 2816).take 128) = true := by
  decide +kernel

theorem source_chunk_23 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 2944
      ((rows.drop 2944).take 128) = true := by
  decide +kernel

theorem target_chunk_23 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 2944
      ((rows.drop 2944).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
