import Sarkozy.OddOrderChunks437.Chunk02

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 3072 through 4095, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_24 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3072
      ((rows.drop 3072).take 128) = true := by
  decide +kernel

theorem target_chunk_24 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3072
      ((rows.drop 3072).take 128) = true := by
  decide +kernel

theorem source_chunk_25 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3200
      ((rows.drop 3200).take 128) = true := by
  decide +kernel

theorem target_chunk_25 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3200
      ((rows.drop 3200).take 128) = true := by
  decide +kernel

theorem source_chunk_26 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3328
      ((rows.drop 3328).take 128) = true := by
  decide +kernel

theorem target_chunk_26 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3328
      ((rows.drop 3328).take 128) = true := by
  decide +kernel

theorem source_chunk_27 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3456
      ((rows.drop 3456).take 128) = true := by
  decide +kernel

theorem target_chunk_27 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3456
      ((rows.drop 3456).take 128) = true := by
  decide +kernel

theorem source_chunk_28 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3584
      ((rows.drop 3584).take 128) = true := by
  decide +kernel

theorem target_chunk_28 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3584
      ((rows.drop 3584).take 128) = true := by
  decide +kernel

theorem source_chunk_29 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3712
      ((rows.drop 3712).take 128) = true := by
  decide +kernel

theorem target_chunk_29 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3712
      ((rows.drop 3712).take 128) = true := by
  decide +kernel

theorem source_chunk_30 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3840
      ((rows.drop 3840).take 128) = true := by
  decide +kernel

theorem target_chunk_30 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3840
      ((rows.drop 3840).take 128) = true := by
  decide +kernel

theorem source_chunk_31 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 3968
      ((rows.drop 3968).take 128) = true := by
  decide +kernel

theorem target_chunk_31 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 3968
      ((rows.drop 3968).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
