import Sarkozy.OddOrderChunks437.Chunk12

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 13312 through 14335, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_104 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13312
      ((rows.drop 13312).take 128) = true := by
  decide +kernel

theorem target_chunk_104 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13312
      ((rows.drop 13312).take 128) = true := by
  decide +kernel

theorem source_chunk_105 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13440
      ((rows.drop 13440).take 128) = true := by
  decide +kernel

theorem target_chunk_105 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13440
      ((rows.drop 13440).take 128) = true := by
  decide +kernel

theorem source_chunk_106 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13568
      ((rows.drop 13568).take 128) = true := by
  decide +kernel

theorem target_chunk_106 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13568
      ((rows.drop 13568).take 128) = true := by
  decide +kernel

theorem source_chunk_107 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13696
      ((rows.drop 13696).take 128) = true := by
  decide +kernel

theorem target_chunk_107 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13696
      ((rows.drop 13696).take 128) = true := by
  decide +kernel

theorem source_chunk_108 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13824
      ((rows.drop 13824).take 128) = true := by
  decide +kernel

theorem target_chunk_108 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13824
      ((rows.drop 13824).take 128) = true := by
  decide +kernel

theorem source_chunk_109 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 13952
      ((rows.drop 13952).take 128) = true := by
  decide +kernel

theorem target_chunk_109 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 13952
      ((rows.drop 13952).take 128) = true := by
  decide +kernel

theorem source_chunk_110 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14080
      ((rows.drop 14080).take 128) = true := by
  decide +kernel

theorem target_chunk_110 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14080
      ((rows.drop 14080).take 128) = true := by
  decide +kernel

theorem source_chunk_111 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14208
      ((rows.drop 14208).take 128) = true := by
  decide +kernel

theorem target_chunk_111 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14208
      ((rows.drop 14208).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
