import Sarkozy.OddOrderChunks437.Chunk14

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 15360 through 16383, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_120 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15360
      ((rows.drop 15360).take 128) = true := by
  decide +kernel

theorem target_chunk_120 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15360
      ((rows.drop 15360).take 128) = true := by
  decide +kernel

theorem source_chunk_121 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15488
      ((rows.drop 15488).take 128) = true := by
  decide +kernel

theorem target_chunk_121 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15488
      ((rows.drop 15488).take 128) = true := by
  decide +kernel

theorem source_chunk_122 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15616
      ((rows.drop 15616).take 128) = true := by
  decide +kernel

theorem target_chunk_122 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15616
      ((rows.drop 15616).take 128) = true := by
  decide +kernel

theorem source_chunk_123 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15744
      ((rows.drop 15744).take 128) = true := by
  decide +kernel

theorem target_chunk_123 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15744
      ((rows.drop 15744).take 128) = true := by
  decide +kernel

theorem source_chunk_124 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15872
      ((rows.drop 15872).take 128) = true := by
  decide +kernel

theorem target_chunk_124 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15872
      ((rows.drop 15872).take 128) = true := by
  decide +kernel

theorem source_chunk_125 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16000
      ((rows.drop 16000).take 128) = true := by
  decide +kernel

theorem target_chunk_125 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16000
      ((rows.drop 16000).take 128) = true := by
  decide +kernel

theorem source_chunk_126 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16128
      ((rows.drop 16128).take 128) = true := by
  decide +kernel

theorem target_chunk_126 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16128
      ((rows.drop 16128).take 128) = true := by
  decide +kernel

theorem source_chunk_127 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 16256
      ((rows.drop 16256).take 128) = true := by
  decide +kernel

theorem target_chunk_127 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 16256
      ((rows.drop 16256).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
