import Sarkozy.OddOrderChunks437.Chunk08

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 9216 through 10239, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_72 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9216
      ((rows.drop 9216).take 128) = true := by
  decide +kernel

theorem target_chunk_72 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9216
      ((rows.drop 9216).take 128) = true := by
  decide +kernel

theorem source_chunk_73 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9344
      ((rows.drop 9344).take 128) = true := by
  decide +kernel

theorem target_chunk_73 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9344
      ((rows.drop 9344).take 128) = true := by
  decide +kernel

theorem source_chunk_74 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9472
      ((rows.drop 9472).take 128) = true := by
  decide +kernel

theorem target_chunk_74 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9472
      ((rows.drop 9472).take 128) = true := by
  decide +kernel

theorem source_chunk_75 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9600
      ((rows.drop 9600).take 128) = true := by
  decide +kernel

theorem target_chunk_75 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9600
      ((rows.drop 9600).take 128) = true := by
  decide +kernel

theorem source_chunk_76 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9728
      ((rows.drop 9728).take 128) = true := by
  decide +kernel

theorem target_chunk_76 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9728
      ((rows.drop 9728).take 128) = true := by
  decide +kernel

theorem source_chunk_77 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9856
      ((rows.drop 9856).take 128) = true := by
  decide +kernel

theorem target_chunk_77 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9856
      ((rows.drop 9856).take 128) = true := by
  decide +kernel

theorem source_chunk_78 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9984
      ((rows.drop 9984).take 128) = true := by
  decide +kernel

theorem target_chunk_78 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9984
      ((rows.drop 9984).take 128) = true := by
  decide +kernel

theorem source_chunk_79 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 10112
      ((rows.drop 10112).take 128) = true := by
  decide +kernel

theorem target_chunk_79 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 10112
      ((rows.drop 10112).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
