import Sarkozy.OddOrderChunks437.Chunk07

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 8192 through 9215, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_64 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8192
      ((rows.drop 8192).take 128) = true := by
  decide +kernel

theorem target_chunk_64 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8192
      ((rows.drop 8192).take 128) = true := by
  decide +kernel

theorem source_chunk_65 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8320
      ((rows.drop 8320).take 128) = true := by
  decide +kernel

theorem target_chunk_65 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8320
      ((rows.drop 8320).take 128) = true := by
  decide +kernel

theorem source_chunk_66 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8448
      ((rows.drop 8448).take 128) = true := by
  decide +kernel

theorem target_chunk_66 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8448
      ((rows.drop 8448).take 128) = true := by
  decide +kernel

theorem source_chunk_67 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8576
      ((rows.drop 8576).take 128) = true := by
  decide +kernel

theorem target_chunk_67 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8576
      ((rows.drop 8576).take 128) = true := by
  decide +kernel

theorem source_chunk_68 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8704
      ((rows.drop 8704).take 128) = true := by
  decide +kernel

theorem target_chunk_68 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8704
      ((rows.drop 8704).take 128) = true := by
  decide +kernel

theorem source_chunk_69 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8832
      ((rows.drop 8832).take 128) = true := by
  decide +kernel

theorem target_chunk_69 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8832
      ((rows.drop 8832).take 128) = true := by
  decide +kernel

theorem source_chunk_70 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 8960
      ((rows.drop 8960).take 128) = true := by
  decide +kernel

theorem target_chunk_70 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 8960
      ((rows.drop 8960).take 128) = true := by
  decide +kernel

theorem source_chunk_71 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 9088
      ((rows.drop 9088).take 128) = true := by
  decide +kernel

theorem target_chunk_71 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 9088
      ((rows.drop 9088).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
