import Sarkozy.OddOrderChunks437.Chunk00

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 1024 through 2047, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_08 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1024
      ((rows.drop 1024).take 128) = true := by
  decide +kernel

theorem target_chunk_08 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1024
      ((rows.drop 1024).take 128) = true := by
  decide +kernel

theorem source_chunk_09 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1152
      ((rows.drop 1152).take 128) = true := by
  decide +kernel

theorem target_chunk_09 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1152
      ((rows.drop 1152).take 128) = true := by
  decide +kernel

theorem source_chunk_10 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1280
      ((rows.drop 1280).take 128) = true := by
  decide +kernel

theorem target_chunk_10 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1280
      ((rows.drop 1280).take 128) = true := by
  decide +kernel

theorem source_chunk_11 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1408
      ((rows.drop 1408).take 128) = true := by
  decide +kernel

theorem target_chunk_11 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1408
      ((rows.drop 1408).take 128) = true := by
  decide +kernel

theorem source_chunk_12 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1536
      ((rows.drop 1536).take 128) = true := by
  decide +kernel

theorem target_chunk_12 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1536
      ((rows.drop 1536).take 128) = true := by
  decide +kernel

theorem source_chunk_13 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1664
      ((rows.drop 1664).take 128) = true := by
  decide +kernel

theorem target_chunk_13 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1664
      ((rows.drop 1664).take 128) = true := by
  decide +kernel

theorem source_chunk_14 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1792
      ((rows.drop 1792).take 128) = true := by
  decide +kernel

theorem target_chunk_14 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1792
      ((rows.drop 1792).take 128) = true := by
  decide +kernel

theorem source_chunk_15 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 1920
      ((rows.drop 1920).take 128) = true := by
  decide +kernel

theorem target_chunk_15 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 1920
      ((rows.drop 1920).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
