import Sarkozy.OddOrderChunks437.Chunk03

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 4096 through 5119, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_32 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4096
      ((rows.drop 4096).take 128) = true := by
  decide +kernel

theorem target_chunk_32 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4096
      ((rows.drop 4096).take 128) = true := by
  decide +kernel

theorem source_chunk_33 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4224
      ((rows.drop 4224).take 128) = true := by
  decide +kernel

theorem target_chunk_33 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4224
      ((rows.drop 4224).take 128) = true := by
  decide +kernel

theorem source_chunk_34 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4352
      ((rows.drop 4352).take 128) = true := by
  decide +kernel

theorem target_chunk_34 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4352
      ((rows.drop 4352).take 128) = true := by
  decide +kernel

theorem source_chunk_35 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4480
      ((rows.drop 4480).take 128) = true := by
  decide +kernel

theorem target_chunk_35 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4480
      ((rows.drop 4480).take 128) = true := by
  decide +kernel

theorem source_chunk_36 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4608
      ((rows.drop 4608).take 128) = true := by
  decide +kernel

theorem target_chunk_36 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4608
      ((rows.drop 4608).take 128) = true := by
  decide +kernel

theorem source_chunk_37 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4736
      ((rows.drop 4736).take 128) = true := by
  decide +kernel

theorem target_chunk_37 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4736
      ((rows.drop 4736).take 128) = true := by
  decide +kernel

theorem source_chunk_38 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4864
      ((rows.drop 4864).take 128) = true := by
  decide +kernel

theorem target_chunk_38 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4864
      ((rows.drop 4864).take 128) = true := by
  decide +kernel

theorem source_chunk_39 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 4992
      ((rows.drop 4992).take 128) = true := by
  decide +kernel

theorem target_chunk_39 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 4992
      ((rows.drop 4992).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
