import Sarkozy.OddOrderChunks437.Chunk13

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 14336 through 15359, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_112 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14336
      ((rows.drop 14336).take 128) = true := by
  decide +kernel

theorem target_chunk_112 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14336
      ((rows.drop 14336).take 128) = true := by
  decide +kernel

theorem source_chunk_113 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14464
      ((rows.drop 14464).take 128) = true := by
  decide +kernel

theorem target_chunk_113 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14464
      ((rows.drop 14464).take 128) = true := by
  decide +kernel

theorem source_chunk_114 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14592
      ((rows.drop 14592).take 128) = true := by
  decide +kernel

theorem target_chunk_114 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14592
      ((rows.drop 14592).take 128) = true := by
  decide +kernel

theorem source_chunk_115 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14720
      ((rows.drop 14720).take 128) = true := by
  decide +kernel

theorem target_chunk_115 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14720
      ((rows.drop 14720).take 128) = true := by
  decide +kernel

theorem source_chunk_116 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14848
      ((rows.drop 14848).take 128) = true := by
  decide +kernel

theorem target_chunk_116 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14848
      ((rows.drop 14848).take 128) = true := by
  decide +kernel

theorem source_chunk_117 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 14976
      ((rows.drop 14976).take 128) = true := by
  decide +kernel

theorem target_chunk_117 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 14976
      ((rows.drop 14976).take 128) = true := by
  decide +kernel

theorem source_chunk_118 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15104
      ((rows.drop 15104).take 128) = true := by
  decide +kernel

theorem target_chunk_118 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15104
      ((rows.drop 15104).take 128) = true := by
  decide +kernel

theorem source_chunk_119 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 15232
      ((rows.drop 15232).take 128) = true := by
  decide +kernel

theorem target_chunk_119 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 15232
      ((rows.drop 15232).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
