import Sarkozy.OddOrderChunks437.Chunk05

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows 6144 through 7167, inclusive.
Each block of at most 128 rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem source_chunk_48 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6144
      ((rows.drop 6144).take 128) = true := by
  decide +kernel

theorem target_chunk_48 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6144
      ((rows.drop 6144).take 128) = true := by
  decide +kernel

theorem source_chunk_49 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6272
      ((rows.drop 6272).take 128) = true := by
  decide +kernel

theorem target_chunk_49 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6272
      ((rows.drop 6272).take 128) = true := by
  decide +kernel

theorem source_chunk_50 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6400
      ((rows.drop 6400).take 128) = true := by
  decide +kernel

theorem target_chunk_50 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6400
      ((rows.drop 6400).take 128) = true := by
  decide +kernel

theorem source_chunk_51 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6528
      ((rows.drop 6528).take 128) = true := by
  decide +kernel

theorem target_chunk_51 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6528
      ((rows.drop 6528).take 128) = true := by
  decide +kernel

theorem source_chunk_52 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6656
      ((rows.drop 6656).take 128) = true := by
  decide +kernel

theorem target_chunk_52 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6656
      ((rows.drop 6656).take 128) = true := by
  decide +kernel

theorem source_chunk_53 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6784
      ((rows.drop 6784).take 128) = true := by
  decide +kernel

theorem target_chunk_53 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6784
      ((rows.drop 6784).take 128) = true := by
  decide +kernel

theorem source_chunk_54 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 6912
      ((rows.drop 6912).take 128) = true := by
  decide +kernel

theorem target_chunk_54 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 6912
      ((rows.drop 6912).take 128) = true := by
  decide +kernel

theorem source_chunk_55 :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 7040
      ((rows.drop 7040).take 128) = true := by
  decide +kernel

theorem target_chunk_55 :
    allIndexed (fastTargetCheck 19683 19 23 3 G19 G23 endpointTable) 7040
      ((rows.drop 7040).take 128) = true := by
  decide +kernel

end

end Sarkozy.OddOrder437
