#!/usr/bin/env python3
"""Generate a compressed, kernel-checkable 437 edge-order certificate.

The source is the pinned reconstructed q437-depth3-final.json certificate.
Rows are sorted by right endpoint. Prefix masks deliberately have only a
one-sided proof interface: all matching source bits must be included.
The Lean kernel, not this generator, checks acceptance of the resulting data.
"""
from __future__ import annotations
from bisect import bisect_right
from hashlib import sha256
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'research-notes/odd-push/q437-depth3-final.json'
EXPECTED_SHA = '7abd0c007c42fa1a5484ea8a4d02c56b04898209f74a0403c5503c03395e58d3'
DEST = ROOT / 'Sarkozy/OddOrderData437.lean'


def nat_literal(value):
    """Factor trailing zero bits when a shift is shorter than a hex literal.

    Lean's built-in natural-number shift reconstructs exactly the same mask;
    the existing kernel checks still verify every source and target row.
    """
    literal = f'0x{value:x}'
    if not value:
        return literal
    shift = (value & -value).bit_length() - 1
    shifted = f'(0x{value >> shift:x} <<< {shift})'
    return shifted if len(shifted) < len(literal) else literal


def tree(entries):
    if not entries:
        return '.empty'
    middle = len(entries) // 2
    key, value = entries[middle]
    return f'(.node\n{tree(entries[:middle])}\n{key} {nat_literal(value)}\n{tree(entries[middle+1:])})'


def key(p, digits):
    out = 1
    for digit in digits:
        out = p * out + digit
    return out


def digits(p, a):
    return [(a // p**d) % p for d in range(3)]


def main():
    raw = SOURCE.read_bytes()
    if sha256(raw).hexdigest() != EXPECTED_SHA:
        raise ValueError('Unexpected q437-depth3-final.json source hash')
    data = json.loads(raw)
    if data['primes'] != [19,23] or data['depth'] != 3 or data['width_denominator'] != 10**16:
        raise ValueError('Unexpected certificate parameters')
    if not len(data['points']) == len(data['start_numerators']) == len(data['width_numerators']) == 19683:
        raise ValueError('Inconsistent row counts')
    rows = []
    for point, start, width in zip(data['points'], data['start_numerators'], data['width_numerators']):
        if len(point) != 2 or any(len(word) != 3 for word in point):
            raise ValueError('Unexpected digit-word dimensions')
        if any(not isinstance(digit, int) or not 0 <= digit < prime
               for prime, word in zip([19,23], point) for digit in word):
            raise ValueError('Noncanonical digit')
        if not isinstance(start, int) or not isinstance(width, int) or not (0 <= start and 0 < width < 10**16 and start+width <= 10**16):
            raise ValueError('Invalid integer interval')
        a,b = [sum(digit*p**d for d,digit in enumerate(word))
               for p,word in zip([19,23],point)]
        rows.append((a,b,start,width))
    if len(rows) != 19683:
        raise ValueError('Unexpected row count')
    rows.sort(key=lambda r: (r[2] + r[3], r[0] + 6859*r[1]))
    if len({(r[0], r[1]) for r in rows}) != len(rows):
        raise ValueError('Repeated point')
    ends = [r[2] + r[3] for r in rows]
    cuts = [bisect_right(ends, r[2]) for r in rows]
    masks = []
    for c,p in enumerate([19,23]):
        table = {}
        for i,row in enumerate(rows):
            word = digits(p,row[c])
            for d in range(1,4):
                code = key(p,word[:d])
                table[code] = table.get(code,0) | 1 << i
        masks.append(table)
    for i,row in enumerate(rows):
        incoming = (1 << len(rows))-1
        for c,p in enumerate([19,23]):
            word = digits(p,row[c])
            mask = masks[c][key(p,word)]
            for d,b in enumerate(word):
                for z in range(p):
                    candidate = (b-z*z)%p
                    if candidate != b:
                        mask |= masks[c].get(key(p,word[:d]+[candidate]),0)
            incoming &= mask
        allowed = ((1 << cuts[i])-1) | (1 << i)
        if incoming & allowed != incoming:
            raise ValueError(f'Failed compressed target check at row {i}')
    header = f'''import Sarkozy.OddOrderCertificate

/-!
# Compressed edge-order data for the 437 low alphabet

Generated by `scripts/generate-odd437-order.py` from the pinned
`research-notes/odd-push/q437-depth3-final.json`.
Source SHA256: `{EXPECTED_SHA}`.
Rows are sorted by increasing right endpoint. Each row stores its cutoff:
the number of source endpoints at most its start. The prefix masks and the
endpoint table are untrusted data checked by the theorems below.
Trailing zero bits in large masks are factored into natural-number shifts.
This only shortens the exact data; the kernel checks the reconstructed masks.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

/-- Endpoint-sorted rows and certified-prefix cutoff proposals. -/
noncomputable def rows : List Entry := [
'''
    literal = ',\n'.join(f'  ((({a}, {b}), ({s}, {w})), {cut})'
                        for (a,b,s,w),cut in zip(rows,cuts))
    output = header + literal + '\n]\n\n'
    output += '/-- Masks for nonempty base-19 low prefixes. -/\nnoncomputable def table19 : MaskTree :=\n'
    output += tree(sorted(masks[0].items())) + '\n\n'
    output += '/-- Masks for nonempty base-23 low prefixes. -/\nnoncomputable def table23 : MaskTree :=\n'
    output += tree(sorted(masks[1].items())) + '\n\n'
    output += '/-- Right endpoints indexed by rank. -/\nnoncomputable def endpointTable : MaskTree :=\n'
    output += tree(list(enumerate(ends))) + '\n\n'
    output += 'end Sarkozy.OddOrder437\n'
    DEST.write_text(output)
    print(json.dumps({'rows':len(rows),'prefix_nodes':[len(t) for t in masks],
                      'endpoint_nodes':len(ends),'lean_bytes':len(output.encode()),
                      'largest_endpoint':max(ends),'destination':str(DEST)},indent=2))


if __name__ == '__main__':
    main()
