#!/usr/bin/env python3
"""Propose kernel-checkable endpoint power certificates for all 437 widths.

The Decimal calculation only proposes downward endpoints; exact rational
checks validate the proposals in Python, and the emitted Lean proofs validate
every entry again with decide +kernel. Sequential chunk modules keep the
large finite checks separate. The original geometry is linked independently.
"""
from __future__ import annotations
import argparse
from collections import Counter
from decimal import Decimal, localcontext, ROUND_FLOOR
from fractions import Fraction
import hashlib
import json
from math import isqrt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'research-notes/odd-push/q437-depth3-final.json'
DEST = ROOT / 'lean-formalization/Sarkozy'
SHA256 = '7abd0c007c42fa1a5484ea8a4d02c56b04898209f74a0403c5503c03395e58d3'
D = 10**26
WIDTH_DENOMINATOR = 10**16
LOWER_DENOMINATOR = 10**12
POWER = Fraction(67871875356, 10**12)
STEPS = 10
ROOT_POWER = 2**STEPS
DENOMINATOR_POWER = D**(ROOT_POWER-1)
CHUNK_SIZE = 128
BLOCKS_PER_MODULE = 8
EXPECTED_SUM = 12261229628963862


def log_bounds(x):
    z = 1-x
    s = sum((z**k/Fraction(k) for k in range(1, 9)), Fraction())
    error = z**9/x
    return -s-error, -s+error


def certificate(width, multiplicity):
    with localcontext() as ctx:
        ctx.prec = 80
        f = Decimal(POWER.numerator)/Decimal(POWER.denominator)
        q = Decimal(width)/Decimal(WIDTH_DENOMINATOR)
        y = int(((q.ln()*f).exp()*LOWER_DENOMINATOR).to_integral_value(rounding=ROUND_FLOOR))-1
    a0, b0 = width*(D//WIDTH_DENOMINATOR), y*(D//LOWER_DENOMINATOR)
    a, b = a0, b0
    for _ in range(STEPS):
        a = isqrt(a*D)
        z = b*D
        b = isqrt(z)
        b += b*b < z
    assert a0 > 0 and b0 > 0 and 0 < a <= D and 0 < b <= D
    assert log_bounds(Fraction(b,D))[1] <= POWER*log_bounds(Fraction(a,D))[0]
    assert a**ROOT_POWER <= a0*DENOMINATOR_POWER
    assert b0*DENOMINATOR_POWER <= b**ROOT_POWER
    return width, multiplicity, y, a0, b0, a, b


def lean_entry(e):
    w, m, y, a0, b0, low, high = e
    # Only final root endpoints are stored; Lean checks their 1024th powers.
    return f'  momentEntry {w} {m} {y} {hex(low)} {hex(high)}'


def generate_chunk(chunk, k):
    previous='Sarkozy.Odd437MomentChecker' if k==0 else f'Sarkozy.Odd437MomentChunks.Chunk{k-1:03d}'
    weighted=sum(e[1]*e[2] for e in chunk)
    parts=[f'''import {previous}

/-! Kernel-checked 437 moment block {k}; generated by scripts/generate-odd437-moments.py. -/
namespace Sarkozy.Odd437.MomentChunk{k:03d}

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

private noncomputable def entries : List MomentEntry := [
''',',\n'.join(map(lean_entry,chunk)),''']

private theorem entries_checked : entries.all momentEntryCheck = true := by
  decide +kernel

/-- The exact widths and multiplicities certified in this block. -/
noncomputable def histogram : List (ℕ × ℕ) := [
''', ',\n'.join(f'  ({e[0]}, {e[1]})' for e in chunk), ''']

private theorem histogram_eq_entries :
    histogram = entries.map (fun e => (e.width, e.multiplicity)) := by
  decide +kernel

''', f'''private theorem lower_numerator_sum :
    (entries.map (fun e => e.multiplicity * e.lower)).sum = {weighted} := by
  decide +kernel

/-- Analytic moment bound obtained from all the exact checks in this block. -/
theorem lower_bound :
    ({weighted} / 1000000000000 : ℝ) ≤
      (histogram.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (67871875356 / 1000000000000 : ℝ))).sum := by
  have h := moment_entries_lower entries entries_checked
  rw [lower_numerator_sum] at h
  rw [histogram_eq_entries, List.map_map]
  simpa only [Function.comp_def, Nat.cast_ofNat] using h

end Sarkozy.Odd437.MomentChunk{k:03d}
''']
    return ''.join(parts)


def generate_main(chunks):
    block_names=[f'MomentChunk{k:03d}' for k in range(len(chunks))]
    weighted=[sum(e[1]*e[2] for e in chunk) for chunk in chunks]
    total=sum(weighted)
    parts=[f'''import Sarkozy.Odd437MomentChunks.Chunk{(len(chunks)-1)//BLOCKS_PER_MODULE:03d}

/-!
# Certified real-power moment of the complete 437 width histogram

Generated by `scripts/generate-odd437-moments.py` from the pinned source
`research-notes/odd-push/q437-depth3-final.json`, SHA256
`{SHA256}`.

The {sum(map(len,chunks)):,} distinct widths cover all 19,683 points. Each block
checks its initial scalings, endpoint powers, integer Taylor comparison and exact
weighted sum inside Lean's kernel. This module adds those proved bounds.
Correspondence to the geometric rows and edge ordering are proved separately.
-/

namespace Sarkozy.Odd437

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

private noncomputable def momentBlocks : List MomentBlock := [
''',',\n'.join(f'  ({n}.histogram, {w})' for n,w in zip(block_names,weighted)), ''']

/-- All 18,908 distinct widths, sorted increasingly, with exact multiplicities. -/
noncomputable def momentHistogram : List (ℕ × ℕ) := momentBlocks.flatMap Prod.fst

private theorem blocks_lower :
    ∀ b ∈ momentBlocks, (b.2 : ℝ) / 1000000000000 ≤
      (b.1.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (67871875356 / 1000000000000 : ℝ))).sum := by
  simp only [momentBlocks, List.forall_mem_cons]
  exact ⟨''', ',\n    '.join(n+'.lower_bound' for n in block_names), ''', by intro x hx; cases hx⟩

''',f'''private theorem blocks_lower_sum :
    (momentBlocks.map Prod.snd).sum = {total} := by
  decide +kernel

/-- The actual histogram meets the explicit scalar target moment bound. -/
theorem moment_histogram_lower_bound :
    ({total} / 1000000000000 : ℝ) ≤
      (momentHistogram.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 10000000000000000) ^
          (67871875356 / 1000000000000 : ℝ))).sum := by
  have h := moment_blocks_lower momentBlocks blocks_lower
  rw [blocks_lower_sum] at h
  simpa only [momentHistogram, Nat.cast_ofNat] using h

end Sarkozy.Odd437
''']
    return ''.join(parts)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir',type=Path,default=DEST)
    parser.add_argument('--smoke-rows',type=int,default=None,
                        help='For a temporary prototype only; requires a different output directory')
    args=parser.parse_args()
    if args.smoke_rows is not None and (args.smoke_rows<=0 or args.output_dir.resolve()==DEST.resolve()):
        parser.error('--smoke-rows needs a positive count and a nonproduction output directory')
    raw=SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=SHA256:raise ValueError('Unexpected source hash')
    data=json.loads(raw)
    if data['width_denominator']!=WIDTH_DENOMINATOR or len(data['width_numerators'])!=19683:
        raise ValueError('Unexpected source parameters')
    hist=sorted(Counter(data['width_numerators']).items())
    assert len(hist)==18908 and sum(m for _,m in hist)==19683
    if args.smoke_rows is not None:hist=hist[:args.smoke_rows]
    entries=[certificate(w,m) for w,m in hist]
    weighted=sum(e[1]*e[2] for e in entries)
    if args.smoke_rows is None:assert weighted==EXPECTED_SUM,(weighted,EXPECTED_SUM)
    chunks=[entries[k:k+CHUNK_SIZE] for k in range(0,len(entries),CHUNK_SIZE)]
    chunkdir=args.output_dir/'Odd437MomentChunks';chunkdir.mkdir(parents=True,exist_ok=True)
    totalbytes=0
    modules=[chunks[k:k+BLOCKS_PER_MODULE] for k in range(0,len(chunks),BLOCKS_PER_MODULE)]
    for old in chunkdir.glob('Chunk[0-9][0-9][0-9].lean'):
        if int(old.stem[5:])>=len(modules):old.unlink()
    for k,blocks in enumerate(modules):
        previous='Sarkozy.Odd437MomentChecker' if k==0 else f'Sarkozy.Odd437MomentChunks.Chunk{k-1:03d}'
        text=f'import {previous}\n'
        for j,block in enumerate(blocks):
            text+=generate_chunk(block,k*BLOCKS_PER_MODULE+j).split('\n',1)[1]
        (chunkdir/f'Chunk{k:03d}.lean').write_text(text);totalbytes+=len(text.encode())
    text=generate_main(chunks);(args.output_dir/'Odd437MomentData.lean').write_text(text);totalbytes+=len(text.encode())
    print(json.dumps({'output':str(args.output_dir),'source_sha256':SHA256,'distinct_widths':len(entries),
                      'weighted_lower_numerator':weighted,'bytes':totalbytes,'blocks':len(chunks),'modules':len(modules),
                      'proposal_root_steps':STEPS,'endpoint_root_power':ROOT_POWER,'sqrt_denominator':D},indent=2))

if __name__=='__main__':main()
