#!/usr/bin/env python3
"""Recreate the packed 215 low-certificate data for Lean.

Only discovery/data conversion happens here. Lean rechecks the resulting
literal data. This generator does not constitute a proof of edge ordering or
of the real-power moment inequality. Those proofs are in OddOrder215 and
Odd215Certificate; Odd215Moment supplies the original packed-row moment.
"""
from __future__ import annotations
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'research-notes/odd-search/q215-depth3-product.json'
SHA256 = 'dae38a756de83c99d65973ff85f23a7068ce6e85a7a4f12400a923f24cf46574'
DEST = ROOT / 'lean-formalization/Sarkozy/OddData215.lean'


def main():
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SHA256:
        raise ValueError('Unexpected odd215 source hash')
    data = json.loads(raw)
    ps, depth, points = data['primes'], data['depth'], data['points']
    nums, denominator = data['width_numerators'], data['width_denominator']
    if ps != [5, 43] or depth != 3 or len(points) != 4913:
        raise ValueError('Unexpected odd215 parameters')
    n = len(points)
    incoming = [(1 << n) - 1 for _ in points]
    for coordinate, p in enumerate(ps):
        qr = {z * z % p for z in range(1, p)}
        groups = {}
        for index, point in enumerate(points):
            word = tuple(point[coordinate])
            for d in range(1, depth + 1):
                prefix = word[:d]
                groups[prefix] = groups.get(prefix, 0) | (1 << index)
        memo = {}
        for index, point in enumerate(points):
            word = tuple(point[coordinate])
            if word not in memo:
                mask = groups[word]
                for d, target_digit in enumerate(word):
                    for square in qr:
                        prefix = word[:d] + ((target_digit - square) % p,)
                        mask |= groups.get(prefix, 0)
                memo[word] = mask
            incoming[index] &= memo[word]
    # Exact longest-path starts, in the original topological row order.
    starts, ends = [], []
    edge_count = 0
    for index, (mask, width) in enumerate(zip(incoming, nums)):
        mask &= ~(1 << index)
        if mask >> index:
            raise ValueError(f'Non-topological source row {index}')
        edge_count += mask.bit_count()
        start = 0
        while mask:
            bit = mask & -mask
            start = max(start, ends[bit.bit_length() - 1])
            mask ^= bit
        starts.append(start)
        ends.append(start + width)
    if max(ends) != data['exact_max_path_numerator']:
        raise ValueError('Reconstructed starts disagree with saved longest path')
    # Sorting by an injective packed key permits a linear duplicate check.
    rows = []
    for point, start, width in zip(points, starts, nums):
        packed = [sum(a * p**d for d, a in enumerate(word))
                  for p, word in zip(ps, point)]
        rows.append(((packed[0], packed[1]), (start, width)))
    rows.sort(key=lambda row: row[0][0] + ps[0]**depth * row[0][1])
    header = f'''import Sarkozy.OddData

/-!
# Actual depth-three low certificate for the 215 component

Generated by `scripts/generate-odd-data.py` from
`research-notes/odd-search/q215-depth3-product.json`.
Source SHA256: `{SHA256}`.

Each row is `((low5, low43), (startNumerator, widthNumerator))`.
Low words use least-significant digits first. Starts are reconstructed by exact
longest paths, then rows are sorted by `low5 + 125 * low43`.
Edge-order checking must use the supplied endpoints independently of row indices.
The literal data below are checked independently by the Lean kernel.
`OddOrder215` and `Odd215Certificate` prove the complete ordering and interval
certificate; `Odd215Moment` proves the moment for these original packed rows.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.Odd215

noncomputable section

/-- Common denominator of all rational interval endpoints. -/
def denominator : ℕ := {denominator}

/-- Reconstructed certificate data; sorted by the packed low-word key. -/
noncomputable def rows : List OddData.Row := [
'''
    literal = ',\n'.join(f'  (({a}, {b}), ({s}, {w}))' for ((a, b), (s, w)) in rows)
    footer = '''
]

/-- There are exactly 17³ indexed rows before lifting. -/
theorem rows_size : rows.length = 4913 := by decide +kernel

/-- Every supplied low word is canonical, every width is positive and less
than one, and every rational interval lies in the unit interval. -/
theorem rows_valid : rows.all (OddData.valid 125 79507 denominator) = true := by
  decide +kernel

/-- The packed-coordinate keys are strictly increasing in the supplied order. -/
theorem rows_sorted : (rows.map (OddData.key 125)).IsChain (· < ·) := by
  decide +kernel

def row (k : Fin 4913) : OddData.Row :=
  rows.get (Fin.cast rows_size.symm k)

def point (k : Fin 4913) (i : Fin 2) : ℕ := ![(row k).1.1, (row k).1.2] i

def start (k : Fin 4913) : ℕ := (row k).2.1

def width (k : Fin 4913) : ℕ := (row k).2.2

theorem denominator_pos : 0 < denominator := by decide +kernel

theorem row_bounds (k : Fin 4913) :
    (row k).1.1 < 125 ∧ (row k).1.2 < 79507 ∧
    0 < width k ∧ width k < denominator ∧ start k + width k ≤ denominator :=
  OddData.bounds_of_list_all 125 79507 denominator rows rows_valid (Fin.cast rows_size.symm k)

theorem point_bounds (k : Fin 4913) (i : Fin 2) :
    point k i < (recordOddPrimes 0 i)^3 := by
  have h := row_bounds k
  fin_cases i
  · change (row k).1.1 < 125
    exact h.1
  · change (row k).1.2 < 79507
    exact h.2.1

theorem point_injective : Function.Injective point := by
  intro a b hab
  have hpair : (row a).1 = (row b).1 := by
    apply Prod.ext
    · exact congrFun hab 0
    · exact congrFun hab 1
  have hind := OddData.pair_injective_of_sorted 125 rows rows_sorted hpair
  exact Fin.cast_injective _ hind

theorem width_bounds (k : Fin 4913) : 0 < width k ∧ width k < denominator :=
  ⟨(row_bounds k).2.2.1, (row_bounds k).2.2.2.1⟩

theorem endpoint_bound (k : Fin 4913) : start k + width k ≤ denominator :=
  (row_bounds k).2.2.2.2

end

end Sarkozy.Odd215
''' 
    DEST.write_text(header + literal + footer)
    print(json.dumps({'source_sha256': SHA256, 'vertices': n,
                      'edges': edge_count, 'max_endpoint': max(ends),
                      'denominator': denominator, 'lean_file': str(DEST)}, indent=2))


if __name__ == '__main__':
    main()
