#!/usr/bin/env python3
"""Generate the fixed-depth comparison for the binary component.

Two integer square-root ladders bound `log a` from below and `log 2` from
above. The depth `m = 10^20` multiplies the logarithm errors, so the ladders
use `D = 10^50` and 80 steps. Python checks the final inequality exactly;
Lean checks every ladder step and the comparison again. Only the
`RecordBinary` section of `BinaryDepth.lean` is replaced.
"""
from fractions import Fraction
from math import isqrt, floor
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT/'research-notes/next-push/binary-cert-0.7580758318008816.json'
OUTPUT = ROOT/'lean-formalization/Sarkozy/BinaryDepth.lean'
D = 10**50
STEPS = 80
OUT = 10**30
ALPHA = Fraction(473797394875551, 625000000000000)


def ladder(first, upper):
    values = [first]
    for _ in range(STEPS):
        radicand = values[-1]*D
        root = isqrt(radicand)
        if upper and root*root < radicand:
            root += 1
        values.append(root)
    return values


def rows(values):
    return ',\n    '.join(', '.join(map(str, values[j:j+3])) for j in range(0, len(values), 3))


def main():
    data = json.loads(SOURCE.read_text())
    growth, f, depth = Fraction(data['a']), Fraction(data['f']), int(data['depth'])
    assert f == Fraction(1549247890379023302829202, 10**25)
    assert (growth*D).denominator == 1
    lo = ladder((growth*D).numerator, False)
    hi = ladder(2*D, True)
    exact_lo = (1-Fraction(D, lo[-1]))*2**STEPS
    exact_hi = (Fraction(hi[-1], D)-1)*2**STEPS
    L = Fraction(floor(exact_lo*OUT), OUT)
    U = Fraction(-floor(-exact_hi*OUT), OUT)
    bound = -2*U+(depth-1)*L-f*U-ALPHA*depth*2*U
    margin = floor(bound)-1
    assert margin > 0
    section = f'''namespace RecordBinary

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

-- Generated by `scripts/generate-binary-depth.py`.
-- The next entry is the integer square root of the current entry times D.
private def growthLogLower : Fin {STEPS+1} → ℕ :=
  ![{rows(lo)}]

-- The next entry is the ceiling of that integer square root.
private def twoLogUpper : Fin {STEPS+1} → ℕ :=
  ![{rows(hi)}]

theorem lower_log_growth : ({L.numerator} / {L.denominator} : ℝ) ≤ Real.log growth := by
  have h := log_lower_of_integer_quotient_ladder {D} growthLogLower
    (by decide) (by decide) (by decide)
  have hfirst : growthLogLower 0 = {lo[0]} := by decide
  have hend : growthLogLower (Fin.last {STEPS}) = {lo[-1]} := by decide
  rw [hfirst, hend] at h
  have hg : (({lo[0]} : ℕ) : ℝ) /
      (({D} : ℕ) : ℝ) = growth := by norm_num [growth]
  rw [hg] at h
  exact (show ({L.numerator} / {L.denominator} : ℝ) ≤ _ by norm_num).trans h

theorem upper_log_two : Real.log (2 : ℝ) ≤ {U.numerator} / {U.denominator} := by
  have h := log_upper_of_integer_ladder 2 {D} twoLogUpper
    (by decide) (by decide) (by decide) (by decide)
  have hend : twoLogUpper (Fin.last {STEPS}) = {hi[-1]} := by decide
  rw [hend] at h
  exact h.trans (by norm_num)

/-- An explicit margin for the weakened initialization constant `c = 1/4`. -/
theorem depth_margin :
    ({margin} : ℝ) ≤ Real.log (1/4 : ℝ) +
      ((depth-1 : ℕ) : ℝ)*Real.log growth - (componentPowers 8)*Real.log 2 -
      targetExponent*(depth : ℝ)*Real.log 4 := by
  have hg := lower_log_growth
  have htwo := upper_log_two
  have hfour : Real.log (4 : ℝ) = 2*Real.log 2 := by
    rw [show (4 : ℝ) = (2 : ℝ)^2 by norm_num, Real.log_pow]
    norm_num
  have hquarter : Real.log (1/4 : ℝ) = -2*Real.log 2 := by
    rw [one_div, Real.log_inv, hfour]
    ring
  have hpower : componentPowers 8 = (1549247890379023302829202 / 10000000000000000000000000 : ℝ) := by rfl
  rw [hquarter, hfour, hpower]
  norm_num [depth, targetExponent]
  nlinarith

/-- The fixed-depth condition is fully proved, with no numerical hypothesis. -/
theorem depth_condition : DepthCondition := by
  unfold DepthCondition
  have h := depth_margin
  linarith

end RecordBinary'''
    text = OUTPUT.read_text()
    begin = text.index('namespace RecordBinary')
    end = text.index('end RecordBinary')+len('end RecordBinary')
    text = text[:begin]+section+text[end:]
    text = text.replace('''Two exact integer square-root ladders, with 52 steps and denominator `10^35`,
bound `log growth` from below and
`log 2` from above.''', f'''Two exact integer square-root ladders, with {STEPS} steps and denominator `10^50`,
bound `log growth` from below and `log 2` from above.''')
    text = text.replace('The depth remains symbolic: the alphabet of depth `10^10` is not expanded.',
                        'The depth remains symbolic: the alphabet of depth `10^20` is not expanded.')
    OUTPUT.write_text(text)
    print(json.dumps({'lower_log_growth': float(L), 'upper_log_two': float(U),
                      'certified_bound': float(bound), 'stated_margin': margin}, indent=2))


if __name__ == '__main__':
    main()
