#!/usr/bin/env python3
"""Propose kernel-checkable endpoint power certificates for all 437 widths.

The Decimal calculation only proposes downward endpoints; exact rational
checks validate the proposals in Python, and the emitted Lean proofs validate
every entry again with decide +kernel. Sequential chunk modules keep the
large finite checks separate. The original geometry is linked independently.
"""
from __future__ import annotations
import argparse
from collections import Counter
from decimal import Decimal, localcontext, ROUND_FLOOR
from fractions import Fraction
import hashlib
import json
from math import isqrt
from pathlib import Path
import sys as _sys
_sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from lean_module import moduleize

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'research-notes/next-push/q437-unequal32s.json'
DEST = ROOT / 'lean-formalization/Sarkozy'
SHA256 = '3ef1e78e59f6e90327bd739c8c114604a352bb4ae7f0faecc6d547b3cd0104bc'
D = 10**30
WIDTH_DENOMINATOR = 10**16
LOWER_DENOMINATOR = 10**24
POWER_NUMERATOR = 681150585658841330427119
POWER_DENOMINATOR = 10**25
POWER = Fraction(POWER_NUMERATOR, POWER_DENOMINATOR)
STEPS = 12
ROOT_POWER = 2**STEPS
DENOMINATOR_POWER = D**(ROOT_POWER-1)
CHUNK_SIZE = 128
BLOCKS_PER_MODULE = 8
POINTS = 3645
DISTINCT = 3337
EXPECTED_SUM = None

CHECKER = '''import Sarkozy.FastPowerCertificate

/-!
# Soundness of the exact (19,23) width-moment checker

The separate finite certificates are generated by
`scripts/generate-odd437-moments.py` from
`research-notes/next-push/q437-unequal32s.json`.
Source SHA256: `@SHA@`.

Decimal arithmetic only proposes lower endpoints. All endpoint power bounds,
Taylor comparisons, initial scalings and weighted sums in those files are checked by
Lean's kernel. Each width is compared through its 4096th root. The
correspondence of this histogram to the packed rows is proved separately; this
file makes no assertion about their edge ordering.
-/

namespace Sarkozy.Odd437

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

/-- The shared certificate row and exact arithmetic checker. -/
abbrev MomentEntry := PowerChecker.MomentEntry
/-- The initial values are fixed by the width and lower numerators. -/
def momentEntry (width multiplicity lower low high : ℕ) : MomentEntry :=
  PowerChecker.MomentEntry.scaled @WSCALE@ @LSCALE@ width multiplicity lower low high

/-- The finite check includes the link from certificate endpoints to the actual width. -/
def momentEntryCheck (e : MomentEntry) : Bool :=
  decide (e.certificate.a0 = e.width * @WSCALE@ ∧
    e.certificate.b0 = e.lower * @LSCALE@) &&
    decide (PowerChecker.EndpointValid @D@ @PN@ @PD@ @N@ e.certificate)

/-- Analytic soundness of one checked row of the histogram. -/
theorem moment_entry_lower (e : MomentEntry) (he : momentEntryCheck e = true) :
    (e.lower : ℝ) / @LD@ ≤
      ((e.width : ℝ) / @WD@) ^ (@PN@ / @PD@ : ℝ) := by
  have hh := Bool.and_eq_true_iff.mp he
  have heq : e.certificate.a0 = e.width * @WSCALE@ ∧
      e.certificate.b0 = e.lower * @LSCALE@ := of_decide_eq_true hh.1
  have hc : PowerChecker.EndpointValid @D@ @PN@ @PD@ @N@ e.certificate :=
    of_decide_eq_true hh.2
  have h := PowerChecker.endpoint_valid_sound hc
  have ha : (e.certificate.a0 : ℝ) / @D@ =
      (e.width : ℝ) / @WD@ := by
    rw [heq.1]
    push_cast
    ring
  have hb : (e.certificate.b0 : ℝ) / @D@ =
      (e.lower : ℝ) / @LD@ := by
    rw [heq.2]
    push_cast
    ring
  norm_num only [Nat.cast_ofNat, Rat.cast_div, Rat.cast_natCast] at h ⊢
  simpa only [ha, hb] using h

/-- Add checked lower endpoints with their natural-number multiplicities. -/
theorem moment_entries_lower (es : List MomentEntry)
    (he : es.all momentEntryCheck = true) :
    (((es.map (fun e => e.multiplicity * e.lower)).sum : ℕ) : ℝ) / @LD@ ≤
      (es.map (fun e => (e.multiplicity : ℝ) *
        ((e.width : ℝ) / @WD@) ^
          (@PN@ / @PD@ : ℝ))).sum := by
  induction es with
  | nil => simp
  | cons e es ih =>
    have hh := Bool.and_eq_true_iff.mp he
    have hp := mul_le_mul_of_nonneg_left (moment_entry_lower e hh.1)
      (Nat.cast_nonneg e.multiplicity : (0 : ℝ) ≤ e.multiplicity)
    have ht := ih hh.2
    simp only [List.map_cons, List.sum_cons, Nat.cast_add, Nat.cast_mul, add_div]
    nlinarith

/-- A histogram and its certified lower numerator. -/
abbrev MomentBlock := List (ℕ × ℕ) × ℕ

/-- Add any finite list of independently proved histogram moment bounds. -/
theorem moment_blocks_lower (bs : List MomentBlock)
    (he : ∀ b ∈ bs, (b.2 : ℝ) / @LD@ ≤
      (b.1.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / @WD@) ^
          (@PN@ / @PD@ : ℝ))).sum) :
    (((bs.map Prod.snd).sum : ℕ) : ℝ) / @LD@ ≤
      ((bs.flatMap Prod.fst).map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / @WD@) ^
          (@PN@ / @PD@ : ℝ))).sum := by
  induction bs with
  | nil => simp
  | cons b bs ih =>
    have hb := he b (by simp)
    have ht := ih (fun c hc => he c (by simp [hc]))
    simp only [List.map_cons, List.sum_cons, Nat.cast_add, add_div,
      List.flatMap_cons, List.map_append, List.sum_append]
    exact add_le_add hb ht

end Sarkozy.Odd437
'''


def fill(template):
    return (template.replace('@WSCALE@', str(D//WIDTH_DENOMINATOR))
            .replace('@LSCALE@', str(D//LOWER_DENOMINATOR)).replace('@D@', str(D))
            .replace('@PN@', str(POWER_NUMERATOR)).replace('@PD@', str(POWER_DENOMINATOR))
            .replace('@N@', str(ROOT_POWER-1)).replace('@LD@', str(LOWER_DENOMINATOR))
            .replace('@WD@', str(WIDTH_DENOMINATOR)).replace('@SHA@', SHA256))


def log_bounds(x):
    z = 1-x
    s = sum((z**k/Fraction(k) for k in range(1, 9)), Fraction())
    error = z**9/x
    return -s-error, -s+error


def root_endpoints(a0, b0):
    a, b = a0, b0
    for _ in range(STEPS):
        a = isqrt(a*D)
        z = b*D
        b = isqrt(z)
        b += b*b < z
    return a, b


def certificate(width, multiplicity):
    a0 = width*(D//WIDTH_DENOMINATOR)
    a, _ = root_endpoints(a0, a0)
    # The proposal is taken just below the certified lower logarithm, so the
    # exact acceptance test below normally succeeds at the first attempt.
    certified = POWER*ROOT_POWER*log_bounds(Fraction(a, D))[0]
    with localcontext() as ctx:
        ctx.prec = 100
        exponent = Decimal(certified.numerator)/Decimal(certified.denominator)-Decimal(10)**-26
        y = int((exponent.exp()*LOWER_DENOMINATOR).to_integral_value(rounding=ROUND_FLOOR))-1
    while True:
        b0 = y*(D//LOWER_DENOMINATOR)
        _, b = root_endpoints(a0, b0)
        if log_bounds(Fraction(b,D))[1] <= POWER*log_bounds(Fraction(a,D))[0]:
            break
        y -= 1
    assert a0 > 0 and b0 > 0 and 0 < a <= D and 0 < b <= D
    assert a**ROOT_POWER <= a0*DENOMINATOR_POWER
    assert b0*DENOMINATOR_POWER <= b**ROOT_POWER
    return width, multiplicity, y, a0, b0, a, b


def lean_entry(e):
    w, m, y, a0, b0, low, high = e
    # Only final root endpoints are stored; Lean checks their 4096th powers.
    return f'  momentEntry {w} {m} {y} {hex(low)} {hex(high)}'


def generate_chunk(chunk, k):
    previous='Sarkozy.Odd437MomentChecker' if k==0 else f'Sarkozy.Odd437MomentChunks.Chunk{k-1:03d}'
    weighted=sum(e[1]*e[2] for e in chunk)
    parts=[f'''import {previous}

/-! Kernel-checked (19,23) moment block {k}; generated by scripts/generate-odd437-moments.py. -/
namespace Sarkozy.Odd437.MomentChunk{k:03d}

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

private noncomputable def entries : List MomentEntry := [
''',',\n'.join(map(lean_entry,chunk)),''']

private theorem entries_checked : entries.all momentEntryCheck = true := by
  decide +kernel

/-- The exact widths and multiplicities certified in this block. -/
noncomputable def histogram : List (ℕ × ℕ) := [
''', ',\n'.join(f'  ({e[0]}, {e[1]})' for e in chunk), ''']

private theorem histogram_eq_entries :
    histogram = entries.map (fun e => (e.width, e.multiplicity)) := by
  decide +kernel

''', f'''private theorem lower_numerator_sum :
    (entries.map (fun e => e.multiplicity * e.lower)).sum = {weighted} := by
  decide +kernel

/-- Analytic moment bound obtained from all the exact checks in this block. -/
theorem lower_bound :
    ({weighted} / {LOWER_DENOMINATOR} : ℝ) ≤
      (histogram.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / {WIDTH_DENOMINATOR}) ^
          ({POWER_NUMERATOR} / {POWER_DENOMINATOR} : ℝ))).sum := by
  have h := moment_entries_lower entries entries_checked
  rw [lower_numerator_sum] at h
  rw [histogram_eq_entries, List.map_map]
  simpa only [Function.comp_def, Nat.cast_ofNat] using h

end Sarkozy.Odd437.MomentChunk{k:03d}
''']
    return ''.join(parts)


def generate_main(chunks):
    block_names=[f'MomentChunk{k:03d}' for k in range(len(chunks))]
    weighted=[sum(e[1]*e[2] for e in chunk) for chunk in chunks]
    total=sum(weighted)
    parts=[f'''import Sarkozy.Odd437MomentChunks.Chunk{(len(chunks)-1)//BLOCKS_PER_MODULE:03d}

/-!
# Certified real-power moment of the complete (19,23) width histogram

Generated by `scripts/generate-odd437-moments.py` from the pinned source
`research-notes/next-push/q437-unequal32s.json`, SHA256
`{SHA256}`.

The {sum(map(len,chunks)):,} distinct widths cover all {POINTS:,} points. Each block
checks its initial scalings, endpoint powers, integer Taylor comparison and exact
weighted sum inside Lean's kernel. This module adds those proved bounds.
Correspondence to the geometric rows and edge ordering are proved separately.
-/

namespace Sarkozy.Odd437

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

private noncomputable def momentBlocks : List MomentBlock := [
''',',\n'.join(f'  ({n}.histogram, {w})' for n,w in zip(block_names,weighted)), f''']

/-- All {DISTINCT:,} distinct widths, sorted increasingly, with exact multiplicities. -/
noncomputable def momentHistogram : List (ℕ × ℕ) := momentBlocks.flatMap Prod.fst

private theorem blocks_lower :
    ∀ b ∈ momentBlocks, (b.2 : ℝ) / {LOWER_DENOMINATOR} ≤
      (b.1.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / {WIDTH_DENOMINATOR}) ^
          ({POWER_NUMERATOR} / {POWER_DENOMINATOR} : ℝ))).sum := by
  simp only [momentBlocks, List.forall_mem_cons]
  exact ⟨''', ',\n    '.join(n+'.lower_bound' for n in block_names), ''', by intro x hx; cases hx⟩

''',f'''private theorem blocks_lower_sum :
    (momentBlocks.map Prod.snd).sum = {total} := by
  decide +kernel

/-- The actual histogram meets the explicit scalar target moment bound. -/
theorem moment_histogram_lower_bound :
    ({total} / {LOWER_DENOMINATOR} : ℝ) ≤
      (momentHistogram.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / {WIDTH_DENOMINATOR}) ^
          ({POWER_NUMERATOR} / {POWER_DENOMINATOR} : ℝ))).sum := by
  have h := moment_blocks_lower momentBlocks blocks_lower
  rw [blocks_lower_sum] at h
  simpa only [momentHistogram, Nat.cast_ofNat] using h

end Sarkozy.Odd437
''']
    return ''.join(parts)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir',type=Path,default=DEST)
    parser.add_argument('--smoke-rows',type=int,default=None,
                        help='For a temporary prototype only; requires a different output directory')
    args=parser.parse_args()
    if args.smoke_rows is not None and (args.smoke_rows<=0 or args.output_dir.resolve()==DEST.resolve()):
        parser.error('--smoke-rows needs a positive count and a nonproduction output directory')
    raw=SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=SHA256:raise ValueError('Unexpected source hash')
    data=json.loads(raw)
    if data['width_denominator']!=WIDTH_DENOMINATOR or len(data['width_numerators'])!=POINTS:
        raise ValueError('Unexpected source parameters')
    hist=sorted(Counter(data['width_numerators']).items())
    assert len(hist)==DISTINCT and sum(m for _,m in hist)==POINTS
    if args.smoke_rows is not None:hist=hist[:args.smoke_rows]
    entries=[certificate(w,m) for w,m in hist]
    weighted=sum(e[1]*e[2] for e in entries)
    if args.smoke_rows is None and EXPECTED_SUM is not None:assert weighted==EXPECTED_SUM,(weighted,EXPECTED_SUM)
    (args.output_dir/'Odd437MomentChecker.lean').write_text(moduleize(fill(CHECKER)))
    chunks=[entries[k:k+CHUNK_SIZE] for k in range(0,len(entries),CHUNK_SIZE)]
    chunkdir=args.output_dir/'Odd437MomentChunks';chunkdir.mkdir(parents=True,exist_ok=True)
    totalbytes=0
    modules=[chunks[k:k+BLOCKS_PER_MODULE] for k in range(0,len(chunks),BLOCKS_PER_MODULE)]
    for old in chunkdir.glob('Chunk[0-9][0-9][0-9].lean'):
        if int(old.stem[5:])>=len(modules):old.unlink()
    for k,blocks in enumerate(modules):
        previous='Sarkozy.Odd437MomentChecker' if k==0 else f'Sarkozy.Odd437MomentChunks.Chunk{k-1:03d}'
        text=f'import {previous}\n'
        for j,block in enumerate(blocks):
            text+=generate_chunk(block,k*BLOCKS_PER_MODULE+j).split('\n',1)[1]
        (chunkdir/f'Chunk{k:03d}.lean').write_text(moduleize(text));totalbytes+=len(text.encode())
    text=generate_main(chunks);(args.output_dir/'Odd437MomentData.lean').write_text(moduleize(text));totalbytes+=len(text.encode())
    print(json.dumps({'output':str(args.output_dir),'source_sha256':SHA256,'distinct_widths':len(entries),
                      'weighted_lower_numerator':weighted,'bytes':totalbytes,'blocks':len(chunks),'modules':len(modules),
                      'proposal_root_steps':STEPS,'endpoint_root_power':ROOT_POWER,'sqrt_denominator':D},indent=2))

if __name__=='__main__':main()
