#!/usr/bin/env python3
"""Encode the actual 437 low-certificate rows for kernel checking in Lean.

This is data conversion, not a trusted verification program. Exact starts are
already present in the pinned source. Keep point/start/width tuples together
when sorting; Lean independently checks the count, bounds and distinctness.
OddOrder437 and Odd437Certificate prove the ordering and full interval
certificate; Odd437Moment supplies the original packed-row moment.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "research-notes/odd-push/q437-depth3-final.json"
SHA256 = "7abd0c007c42fa1a5484ea8a4d02c56b04898209f74a0403c5503c03395e58d3"
DEST = ROOT / "lean-formalization/Sarkozy/OddData437.lean"


def main():
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SHA256:
        raise ValueError("Unexpected odd437 source hash")
    data = json.loads(raw)
    primes, depth = data["primes"], data["depth"]
    points, starts = data["points"], data["start_numerators"]
    widths, denominator = data["width_numerators"], data["width_denominator"]
    if primes != [19, 23] or depth != 3 or len(points) != 19683:
        raise ValueError("Unexpected odd437 parameters")
    if len(starts) != len(points) or len(widths) != len(points):
        raise ValueError("Inconsistent point/start/width lengths")
    rows = []
    for point, start, width in zip(points, starts, widths):
        if len(point) != 2 or any(len(word) != depth for word in point):
            raise ValueError("Unexpected digit-word dimensions")
        if any(not isinstance(digit, int) or not 0 <= digit < prime
               for prime, word in zip(primes, point) for digit in word):
            raise ValueError("Noncanonical digit")
        if not isinstance(start, int) or not isinstance(width, int):
            raise ValueError("Noninteger interval endpoint")
        if not (0 <= start and 0 < width < denominator and start + width <= denominator):
            raise ValueError("Invalid interval bounds")
        packed = [sum(digit * prime**d for d, digit in enumerate(word))
                  for prime, word in zip(primes, point)]
        rows.append(((packed[0], packed[1]), (start, width)))
    rows.sort(key=lambda row: row[0][0] + 6859 * row[0][1])
    keys = [a + 6859 * b for (a, b), _ in rows]
    if any(a >= b for a, b in zip(keys, keys[1:])):
        raise ValueError("Repeated packed low-coordinate pair")
    if max(s + w for _, (s, w) in rows) != data["exact_max_path_numerator"]:
        raise ValueError("Supplied endpoints disagree with saved maximum")
    header = f'''import Sarkozy.OddData

/-!
# Actual depth-three low certificate for the 437 component

Generated by `scripts/generate-odd437-data.py` from
`research-notes/odd-push/q437-depth3-final.json`.
Source SHA256: `{SHA256}`.

Each row is `((low19, low23), (startNumerator, widthNumerator))`.
Low words use least-significant digits first. Point/start/width tuples from the
source are preserved together, then sorted by `low19 + 6859 * low23`.
Edge-order checking must use the supplied endpoints independently of row indices.
The literal data below are checked independently by the Lean kernel.
`OddOrder437` and `Odd437Certificate` prove the complete ordering and interval
certificate; `Odd437Moment` proves the moment for these original packed rows.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.Odd437

noncomputable section

/-- Common denominator of all rational interval endpoints. -/
def denominator : ℕ := {denominator}

/-- Supplied certificate data; sorted by the packed low-word key. -/
noncomputable def rows : List OddData.Row := [
'''
    literal = ',\n'.join(f'  (({a}, {b}), ({s}, {w}))' for ((a, b), (s, w)) in rows)
    footer = '''
]

/-- There are exactly 27³ indexed rows before lifting. -/
theorem rows_size : rows.length = 19683 := by decide +kernel

/-- Every supplied low word is canonical, every width is positive and less
than one, and every rational interval lies in the unit interval. -/
theorem rows_valid : rows.all (OddData.valid 6859 12167 denominator) = true := by
  decide +kernel

/-- The packed-coordinate keys are strictly increasing in the supplied order. -/
theorem rows_sorted : (rows.map (OddData.key 6859)).IsChain (· < ·) := by
  decide +kernel

def row (k : Fin 19683) : OddData.Row :=
  rows.get (Fin.cast rows_size.symm k)

def point (k : Fin 19683) (i : Fin 2) : ℕ := ![(row k).1.1, (row k).1.2] i

def start (k : Fin 19683) : ℕ := (row k).2.1

def width (k : Fin 19683) : ℕ := (row k).2.2

theorem denominator_pos : 0 < denominator := by decide +kernel

theorem row_bounds (k : Fin 19683) :
    (row k).1.1 < 6859 ∧ (row k).1.2 < 12167 ∧
    0 < width k ∧ width k < denominator ∧ start k + width k ≤ denominator :=
  OddData.bounds_of_list_all 6859 12167 denominator rows rows_valid (Fin.cast rows_size.symm k)

theorem point_bounds (k : Fin 19683) (i : Fin 2) :
    point k i < (recordOddPrimes 1 i)^3 := by
  have h := row_bounds k
  fin_cases i
  · change (row k).1.1 < 6859
    exact h.1
  · change (row k).1.2 < 12167
    exact h.2.1

theorem point_injective : Function.Injective point := by
  intro a b hab
  have hpair : (row a).1 = (row b).1 := by
    apply Prod.ext
    · exact congrFun hab 0
    · exact congrFun hab 1
  have hind := OddData.pair_injective_of_sorted 6859 rows rows_sorted hpair
  exact Fin.cast_injective _ hind

theorem width_bounds (k : Fin 19683) : 0 < width k ∧ width k < denominator :=
  ⟨(row_bounds k).2.2.1, (row_bounds k).2.2.2.1⟩

theorem endpoint_bound (k : Fin 19683) : start k + width k ≤ denominator :=
  (row_bounds k).2.2.2.2

end

end Sarkozy.Odd437
'''
    DEST.write_text(header + literal + footer)
    print(json.dumps({"source_sha256": SHA256, "vertices": len(rows),
                      "max_endpoint": max(s + w for _, (s, w) in rows),
                      "denominator": denominator, "lean_file": str(DEST)}, indent=2))


if __name__ == "__main__":
    main()
