#!/usr/bin/env python3
"""Generate the scalar moment thresholds for both odd components.

Each threshold compares the certified lower moment sum `S / 10^24` (read from
the generated moment data) with `F^(2 alpha - 1)`, where `F` is the number of
free words. Integer square-root ladders bound the two logarithms; Lean checks
every ladder step and the final comparison. Python only proposes the data and
checks the same exact inequality before writing.
"""
from __future__ import annotations
from fractions import Fraction
from math import isqrt
from pathlib import Path
import re
import sys as _sys
_sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from lean_module import moduleize

ROOT = Path(__file__).resolve().parents[1]
D = 10**50
STEPS = 80
OUT = 10**30
LOWER_DENOMINATOR = 10**24
ALPHA = Fraction(473797394875551, 625000000000000)


def ladder(first: int, upper: bool) -> list[int]:
    values = [first]
    for _ in range(STEPS):
        radicand = values[-1]*D
        root = isqrt(radicand)
        if upper and root*root < radicand:
            root += 1
        values.append(root)
    return values


def rows(values: list[int]) -> str:
    return ',\n    '.join(', '.join(map(str, values[j:j+3])) for j in range(0, len(values), 3))


def lower_bound(values: list[int]) -> Fraction:
    exact = (1-Fraction(D, values[-1]))*2**STEPS
    return Fraction((exact*OUT).numerator//(exact*OUT).denominator, OUT)


def upper_bound(values: list[int]) -> Fraction:
    exact = (Fraction(values[-1], D)-1)*2**STEPS
    scaled = exact*OUT
    return Fraction(-(-scaled.numerator//scaled.denominator), OUT)


def lean_fraction(q: Fraction) -> str:
    return f'{q.numerator} / {q.denominator}'


def certified_sum(path: Path) -> int:
    text = path.read_text()
    match = re.search(r'theorem moment_histogram_lower_bound :\n    \((\d+) / (\d+) : ℝ\)', text)
    assert match and int(match.group(2)) == LOWER_DENOMINATOR, path
    return int(match.group(1))


def generate(namespace, title, rows_count, moment_module, total, root, root_name,
             base_lean, free_lean, free_cast, free_real, log_power, docs):
    lo = ladder(total*(D//LOWER_DENOMINATOR), False)
    hi = ladder(root*D, True)
    L, U = lower_bound(lo), upper_bound(hi)
    margin = L-(2*ALPHA-1)*log_power*U
    assert margin > 0, margin
    sum_fraction = f'{total} / {LOWER_DENOMINATOR}'
    text = f'''import Sarkozy.BinaryDepth

/-!
# The scalar moment threshold for the {title} certificate

This file proves the target threshold for the explicit proposed lower moment
sum. It does not assume or prove that the {rows_count} widths attain that lower sum;
`{moment_module}` proves that separately.

Generated by `scripts/generate-odd-thresholds.py`. With `D = 10^{len(str(D))-1}`,
the first ladder starts at `{total} * (D / 10^24)` and the second at
`{root} * D`; each later entry is the integer square root of the previous entry
times `D`, rounded up in the second ladder. The rounded log endpoints are the
floor, respectively ceiling, at denominator `10^30` of `2^{STEPS}*(1-D/lo)` and
`2^{STEPS}*(hi/D-1)`. {docs} Every entry and the final comparison are checked by
Lean.
-/

namespace Sarkozy.{namespace}

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

private def sumLogLower : Fin {STEPS+1} → ℕ :=
  ![{rows(lo)}]

private def rootLogUpper : Fin {STEPS+1} → ℕ :=
  ![{rows(hi)}]

private theorem lower_log_sum :
    ({lean_fraction(L)} : ℝ) ≤
      Real.log ({sum_fraction} : ℝ) := by
  have h := log_lower_of_integer_quotient_ladder {D} sumLogLower
    (by decide) (by decide) (by decide)
  have hfirst : sumLogLower 0 = {lo[0]} := by decide
  have hend : sumLogLower (Fin.last {STEPS}) = {lo[-1]} := by decide
  rw [hfirst, hend] at h
  have hq : (({lo[0]} : ℕ) : ℝ) /
      (({D} : ℕ) : ℝ) =
      ({sum_fraction} : ℝ) := by norm_num
  rw [hq] at h
  exact (show ({lean_fraction(L)} : ℝ) ≤ _ by norm_num).trans h

private theorem upper_log_root :
    Real.log ({root_name} : ℝ) ≤ {lean_fraction(U)} := by
  have h := log_upper_of_integer_ladder {root} {D} rootLogUpper
    (by decide) (by decide) (by decide) (by decide)
  have hend : rootLogUpper (Fin.last {STEPS}) = {hi[-1]} := by decide
  rw [hend] at h
  exact h.trans (by norm_num)

/-- The explicit lower moment sum suffices for the full record exponent. -/
theorem moment_threshold :
    ({base_lean} : ℝ)^targetExponent ≤
      ({free_lean} : ℕ) * ({sum_fraction} : ℝ) := by
  apply (Real.log_le_log_iff
    (Real.rpow_pos_of_pos (by norm_num : (0 : ℝ) < {base_lean}) _)
    (by positivity)).mp
  have hcast : (({free_lean} : ℕ) : ℝ) = {free_real} := by norm_num
  rw [hcast, Real.log_rpow (by norm_num : (0 : ℝ) < {base_lean}),
    Real.log_mul (by positivity) (by positivity){free_cast}]
  have hl := lower_log_sum
  have hu := upper_log_root
  norm_num [targetExponent] at *
  nlinarith

end Sarkozy.{namespace}
'''
    return text, L, U, margin


def main():
    s215 = certified_sum(ROOT/'Sarkozy/Odd215MomentData.lean')
    text, L, U, margin = generate(
        'Odd215', '(5,43)', '4,913', 'Odd215Certificate', s215, 215, '215',
        '215^6', '215^3', ', Real.log_pow, Real.log_pow', '(215 : ℝ)^3', 3,
        'Here `F = 215^3`.')
    (ROOT/'Sarkozy/Odd215Threshold.lean').write_text(moduleize(text))
    print('215', float(L), float(U), 'margin', float(margin))
    s437 = certified_sum(ROOT/'Sarkozy/Odd437MomentData.lean')
    text, L, U, margin = generate(
        'Odd437', '(19,23)', '3,645', 'Odd437Certificate', s437, 3628411, '3628411',
        '3628411^2', '3628411', ', Real.log_pow', '(3628411 : ℝ)', 1,
        'Here `F = 19^3 * 23^2 = 3628411`.')
    (ROOT/'Sarkozy/Odd437Threshold.lean').write_text(moduleize(text))
    print('437', float(L), float(U), 'margin', float(margin))


if __name__ == '__main__':
    main()
