#!/usr/bin/env python3
"""Split the actual 437 kernel checks into sequential, independently cached modules."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHUNKS = ROOT / 'Sarkozy/OddOrderChunks437'
N = 19683
BLOCK = 128
COUNT = (N + BLOCK - 1) // BLOCK
GROUP = 8
MODULES = (COUNT + GROUP - 1) // GROUP

BASE = '''import Sarkozy.OddOrderData437
import Sarkozy.OddOrderFast

/-!
# Basic data checks shared by the 437 order-verification chunks

The source and target mask checks are split into sequentially imported chunks
to bound peak kernel evaluation state and preserve completed work in the cache.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

def G19 : List ℤ → ℕ := fastPrefixLookup 19 table19

def G23 : List ℤ → ℕ := fastPrefixLookup 23 table23

def denominator : ℕ := 10000000000000000

theorem rows_size : rows.length = 19683 := by decide +kernel

theorem rows_valid : rows.all (fun r => OddData.valid 6859 12167 denominator r.1) = true := by
  decide +kernel

theorem endpoints_sorted : (rows.map entryEnd).IsChain (· ≤ ·) := by
  decide +kernel

end

end Sarkozy.OddOrder437
'''


def main():
    CHUNKS.mkdir(exist_ok=True)
    (ROOT / 'Sarkozy/OddOrderBase437.lean').write_text(BASE)
    for old in CHUNKS.glob('Chunk*.lean'):
        old.unlink()
    for group in range(MODULES):
        previous = 'Sarkozy.OddOrderBase437' if group == 0 else f'Sarkozy.OddOrderChunks437.Chunk{group-1:02d}'
        first = group * GROUP
        last = min(first + GROUP, COUNT)
        text = f'''import {previous}

/-! Generated by `scripts/generate-odd437-order-chunks.py`.
Kernel checks for rows {first*BLOCK} through {min(last*BLOCK,N)-1}, inclusive.
Each block of at most {BLOCK} rows has a separate kernel-checked proof.
Several blocks share each import to reduce fixed frontend costs; the physical
module import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section
'''
        for i in range(first,last):
            offset = i * BLOCK
            text += f'''
theorem source_chunk_{i:02d} :
    allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) {offset}
      ((rows.drop {offset}).take {BLOCK}) = true := by
  decide +kernel

theorem target_chunk_{i:02d} :
    allIndexed (fastTargetCheck {N} 19 23 3 G19 G23 endpointTable) {offset}
      ((rows.drop {offset}).take {BLOCK}) = true := by
  decide +kernel
'''
        text += '\nend\n\nend Sarkozy.OddOrder437\n'
        (CHUNKS / f'Chunk{group:02d}.lean').write_text(text)
    aggregate = f'''import Sarkozy.OddOrderChunks437.Chunk{MODULES-1:02d}
import Sarkozy.OddOrderChunkLemma

/-!
# Every row of the actual 437 order certificate is checked

The generic block-concatenation theorem combines the independently checked
source and target chunks without reevaluating their certificate computations.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder437

open OddOrder

noncomputable section

theorem sources_checked : allIndexed (sourceCheck 19 23 3 G19 G23 endpointTable) 0 rows = true := by
  apply allIndexed_of_blocks (P := sourceCheck 19 23 3 G19 G23 endpointTable)
    (rows := rows) (b := {BLOCK}) (c := {COUNT}) (by decide) (by rw [rows_size]; decide)
  intro i
  fin_cases i
'''
    aggregate += ''.join(f'  · exact source_chunk_{i:02d}\n' for i in range(COUNT))
    aggregate += f'''
theorem targets_checked_fast :
    allIndexed (fastTargetCheck {N} 19 23 3 G19 G23 endpointTable) 0 rows = true := by
  apply allIndexed_of_blocks (P := fastTargetCheck {N} 19 23 3 G19 G23 endpointTable)
    (rows := rows) (b := {BLOCK}) (c := {COUNT}) (by decide) (by rw [rows_size]; decide)
  intro i
  fin_cases i
'''
    aggregate += ''.join(f'  · exact target_chunk_{i:02d}\n' for i in range(COUNT))
    aggregate += '''
theorem targets_checked :
    allIndexed (targetCheck rows.length 19 23 3 G19 G23 endpointTable) 0 rows = true := by
  simpa only [fastTargetCheck_eq, rows_size] using targets_checked_fast

end

end Sarkozy.OddOrder437
'''
    (ROOT / 'Sarkozy/OddOrderChecks437.lean').write_text(aggregate)
    print(f'Generated {COUNT} separately checked blocks of at most {BLOCK} rows in {MODULES} sequential modules and their aggregate.')


if __name__ == '__main__':
    main()
