#!/usr/bin/env python3
"""Propose exact power certificates for the actual 215 width histogram.

The Decimal calculation only proposes downward endpoints. Python independently
checks exact rational inequalities; the generated Lean file checks them again
inside the kernel. Correspondence to the packed geometric rows is a separate
Lean theorem supplied by the integration module.
"""
from __future__ import annotations
import argparse
from collections import Counter
from decimal import Decimal, localcontext, ROUND_FLOOR
from fractions import Fraction
import hashlib
import json
from math import isqrt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'research-notes/odd-search/q215-depth3-product.json'
DEST = ROOT / 'lean-formalization/Sarkozy/Odd215MomentData.lean'
SHA256 = 'dae38a756de83c99d65973ff85f23a7068ce6e85a7a4f12400a923f24cf46574'
D = 10**26
WIDTH_DENOMINATOR = 10**14
LOWER_DENOMINATOR = 10**12
POWER = Fraction(26537312662, 10**12)
STEPS = 10
ROOT_POWER = 2**STEPS
DENOMINATOR_POWER = D**(ROOT_POWER-1)
CHUNK_SIZE = 64

HEADER = '''import Sarkozy.FastPowerCertificate

/-!
# Certified real-power moment of the actual 215 width histogram

Generated by `scripts/generate-odd215-moments.py` from
`research-notes/odd-search/q215-depth3-product.json`.
Source SHA256: `dae38a756de83c99d65973ff85f23a7068ce6e85a7a4f12400a923f24cf46574`.

Decimal arithmetic only proposes lower endpoints. All endpoint power bounds,
Taylor comparisons, initial scalings and weighted sums below are checked by
Lean's kernel. The correspondence of this histogram to the packed rows is
proved separately; this file makes no assertion about their edge ordering.
-/

namespace Sarkozy.Odd215

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

/-- The shared certificate row and exact arithmetic checker. -/
abbrev MomentEntry := PowerChecker.MomentEntry
/-- The initial values are fixed by the width and lower numerators. -/
def momentEntry (width multiplicity lower low high : ℕ) : MomentEntry :=
  PowerChecker.MomentEntry.scaled 1000000000000 100000000000000 width multiplicity lower low high

/-- The finite check includes the link from certificate endpoints to the actual width. -/
def momentEntryCheck (e : MomentEntry) : Bool :=
  decide (e.certificate.a0 = e.width * 1000000000000 ∧
    e.certificate.b0 = e.lower * 100000000000000) &&
    decide (PowerChecker.EndpointValid 100000000000000000000000000 26537312662 1000000000000 1023 e.certificate)

/-- Analytic soundness of one checked row of the histogram. -/
theorem moment_entry_lower (e : MomentEntry) (he : momentEntryCheck e = true) :
    (e.lower : ℝ) / 1000000000000 ≤
      ((e.width : ℝ) / 100000000000000) ^ (26537312662 / 1000000000000 : ℝ) := by
  have hh := Bool.and_eq_true_iff.mp he
  have heq : e.certificate.a0 = e.width * 1000000000000 ∧
      e.certificate.b0 = e.lower * 100000000000000 := of_decide_eq_true hh.1
  have hc : PowerChecker.EndpointValid 100000000000000000000000000 26537312662 1000000000000 1023 e.certificate :=
    of_decide_eq_true hh.2
  have h := PowerChecker.endpoint_valid_sound hc
  have ha : (e.certificate.a0 : ℝ) / 100000000000000000000000000 =
      (e.width : ℝ) / 100000000000000 := by
    rw [heq.1]
    push_cast
    ring
  have hb : (e.certificate.b0 : ℝ) / 100000000000000000000000000 =
      (e.lower : ℝ) / 1000000000000 := by
    rw [heq.2]
    push_cast
    ring
  norm_num only [Nat.cast_ofNat, Rat.cast_div, Rat.cast_natCast] at h ⊢
  simpa only [ha, hb] using h

/-- Add checked lower endpoints with their natural-number multiplicities. -/
theorem moment_entries_lower (es : List MomentEntry)
    (he : es.all momentEntryCheck = true) :
    (((es.map (fun e => e.multiplicity * e.lower)).sum : ℕ) : ℝ) / 1000000000000 ≤
      (es.map (fun e => (e.multiplicity : ℝ) *
        ((e.width : ℝ) / 100000000000000) ^
          (26537312662 / 1000000000000 : ℝ))).sum := by
  induction es with
  | nil => simp
  | cons e es ih =>
    have hh := Bool.and_eq_true_iff.mp he
    have hp := mul_le_mul_of_nonneg_left (moment_entry_lower e hh.1)
      (Nat.cast_nonneg e.multiplicity : (0 : ℝ) ≤ e.multiplicity)
    have ht := ih hh.2
    simp only [List.map_cons, List.sum_cons, Nat.cast_add, Nat.cast_mul, add_div]
    nlinarith

'''

def log_bounds(x):
    z = 1-x
    s = sum((z**k/Fraction(k) for k in range(1, 9)), Fraction())
    error = z**9/x
    return -s-error, -s+error


def certificate(width, multiplicity):
    with localcontext() as ctx:
        ctx.prec = 80
        f = Decimal(POWER.numerator)/Decimal(POWER.denominator)
        q = Decimal(width)/Decimal(WIDTH_DENOMINATOR)
        y = int(((q.ln()*f).exp()*LOWER_DENOMINATOR).to_integral_value(rounding=ROUND_FLOOR))-1
    a0, b0 = width*(D//WIDTH_DENOMINATOR), y*(D//LOWER_DENOMINATOR)
    a, b = a0, b0
    for _ in range(STEPS):
        a = isqrt(a*D)
        z = b*D
        b = isqrt(z)
        b += b*b < z
    assert a0 > 0 and b0 > 0 and 0 < a <= D and 0 < b <= D
    assert log_bounds(Fraction(b,D))[1] <= POWER*log_bounds(Fraction(a,D))[0]
    assert a**ROOT_POWER <= a0*DENOMINATOR_POWER
    assert b0*DENOMINATOR_POWER <= b**ROOT_POWER
    return width, multiplicity, y, a0, b0, a, b


def lean_entry(e):
    w, m, y, a0, b0, low, high = e
    # Only final root endpoints are stored; Lean checks their 1024th powers.
    return f'  momentEntry {w} {m} {y} {hex(low)} {hex(high)}'


def generate(entries):
    chunks = [entries[k:k+CHUNK_SIZE] for k in range(0,len(entries),CHUNK_SIZE)]
    parts=[HEADER]
    for k,chunk in enumerate(chunks):
        name=f'momentChunk{k:03d}'
        parts.append(f'private noncomputable def {name} : List MomentEntry := [\n'+',\n'.join(map(lean_entry,chunk))+']\n\n')
        parts.append(f'private theorem {name}_checked : {name}.all momentEntryCheck = true := by\n  decide +kernel\n\n')
    names=[f'momentChunk{k:03d}' for k in range(len(chunks))]
    parts.append('/-- All 1,861 distinct widths, sorted increasingly, with exact certificates. -/\n')
    parts.append('noncomputable def momentEntries : List MomentEntry :=\n  '+' ++\n  '.join(names)+'\n\n')
    parts.append('theorem moment_entries_checked : momentEntries.all momentEntryCheck = true := by\n  simp only [momentEntries, List.all_append,\n    '+',\n    '.join(n+'_checked' for n in names)+', Bool.true_and]\n\n')
    parts.append('/-- Explicit width/multiplicity histogram for transport to the geometric rows. -/\n')
    parts.append('noncomputable def momentHistogram : List (ℕ × ℕ) := [\n'+',\n'.join(f'  ({e[0]}, {e[1]})' for e in entries)+']\n\n')
    parts.append('theorem moment_histogram_eq_entries :\n    momentHistogram = momentEntries.map (fun e => (e.width, e.multiplicity)) := by\n  decide +kernel\n\n')
    weighted=sum(e[1]*e[2] for e in entries)
    parts.append(f'theorem moment_lower_numerator_sum :\n    (momentEntries.map (fun e => e.multiplicity * e.lower)).sum = {weighted} := by\n  decide +kernel\n\n')
    parts.append(f'''/-- The checked lower endpoints give the stated real-power histogram moment. -/
theorem moment_histogram_lower_bound :
    ({weighted} / 1000000000000 : ℝ) ≤
      (momentHistogram.map (fun wc => (wc.2 : ℝ) *
        ((wc.1 : ℝ) / 100000000000000) ^
          (26537312662 / 1000000000000 : ℝ))).sum := by
  have h := moment_entries_lower momentEntries moment_entries_checked
  rw [moment_lower_numerator_sum] at h
  rw [moment_histogram_eq_entries, List.map_map]
  simpa only [Function.comp_def, Nat.cast_ofNat] using h

end Sarkozy.Odd215
''')
    return ''.join(parts)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=DEST)
    parser.add_argument('--smoke-rows',type=int,default=None,
                        help='Only for a temporary prototype; requires an explicit different output')
    args=parser.parse_args()
    if args.smoke_rows is not None and (args.smoke_rows <= 0 or args.output.resolve()==DEST.resolve()):
        parser.error('--smoke-rows needs a positive count and a nonproduction output')
    raw=SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=SHA256:
        raise ValueError('Unexpected source hash')
    data=json.loads(raw)
    if data['width_denominator']!=WIDTH_DENOMINATOR or len(data['width_numerators'])!=4913:
        raise ValueError('Unexpected source parameters')
    hist=sorted(Counter(data['width_numerators']).items())
    assert len(hist)==1861 and sum(m for _,m in hist)==4913
    if args.smoke_rows is not None:hist=hist[:args.smoke_rows]
    entries=[certificate(w,m) for w,m in hist]
    weighted=sum(e[1]*e[2] for e in entries)
    if args.smoke_rows is None:assert weighted==4088451159413731
    text=generate(entries)
    args.output.write_text(text)
    print(json.dumps({'output':str(args.output),'source_sha256':SHA256,'distinct_widths':len(entries),
                      'weighted_lower_numerator':weighted,'bytes':len(text.encode()),
                      'proposal_root_steps':STEPS,'endpoint_root_power':ROOT_POWER,'sqrt_denominator':D},indent=2))

if __name__=='__main__':main()
