#!/usr/bin/env python3
"""Split the actual 215 kernel checks into sequential, independently cached modules."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHUNKS = ROOT / 'Sarkozy/OddOrderChunks215'
N = 4913
BLOCK = 128
COUNT = (N + BLOCK - 1) // BLOCK

BASE = '''import Sarkozy.OddOrderData215
import Sarkozy.OddOrderFast

/-!
# Basic data checks shared by the 215 order-verification chunks

The source and target mask checks are split into sequentially imported chunks
to bound peak kernel evaluation state and preserve completed work in the cache.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder215

open OddOrder

noncomputable def G5 : List ℤ → ℕ := fastPrefixLookup 5 table5

noncomputable def G43 : List ℤ → ℕ := fastPrefixLookup 43 table43

def denominator : ℕ := 100000000000000

theorem rows_size : rows.length = 4913 := by decide +kernel

theorem rows_valid : rows.all (fun r => OddData.valid 125 79507 denominator r.1) = true := by
  decide +kernel

theorem endpoints_sorted : (rows.map entryEnd).IsChain (· ≤ ·) := by
  decide +kernel

end Sarkozy.OddOrder215
'''


def main():
    CHUNKS.mkdir(exist_ok=True)
    (ROOT / 'Sarkozy/OddOrderBase215.lean').write_text(BASE)
    for i in range(COUNT):
        previous = 'Sarkozy.OddOrderBase215' if i == 0 else f'Sarkozy.OddOrderChunks215.Chunk{i-1:02d}'
        offset = i * BLOCK
        text = f'''import {previous}

/-! Generated by `scripts/generate-odd-order-chunks.py`.
Kernel checks for rows {offset} through {min(offset+BLOCK,N)-1}, inclusive.
The import chain keeps compilation sequential and peak memory bounded. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Sarkozy.OddOrder215

open OddOrder

theorem source_chunk_{i:02d} :
    allIndexed (sourceCheck 5 43 3 G5 G43 endpointTable) {offset}
      ((rows.drop {offset}).take {BLOCK}) = true := by
  decide +kernel

theorem target_chunk_{i:02d} :
    allIndexed (fastTargetCheck {N} 5 43 3 G5 G43 endpointTable) {offset}
      ((rows.drop {offset}).take {BLOCK}) = true := by
  decide +kernel

end Sarkozy.OddOrder215
'''
        (CHUNKS / f'Chunk{i:02d}.lean').write_text(text)
    aggregate = f'''import Sarkozy.OddOrderChunks215.Chunk{COUNT-1:02d}
import Sarkozy.OddOrderChunkLemma

/-!
# Every row of the actual 215 order certificate is checked

The generic block-concatenation theorem combines the independently checked
source and target chunks without reevaluating their certificate computations.
-/

namespace Sarkozy.OddOrder215

open OddOrder

theorem sources_checked : allIndexed (sourceCheck 5 43 3 G5 G43 endpointTable) 0 rows = true := by
  apply allIndexed_of_blocks (P := sourceCheck 5 43 3 G5 G43 endpointTable)
    (rows := rows) (b := {BLOCK}) (c := {COUNT}) (by decide) (by rw [rows_size]; decide)
  intro i
  fin_cases i
'''
    aggregate += ''.join(f'  · exact source_chunk_{i:02d}\n' for i in range(COUNT))
    aggregate += f'''
theorem targets_checked_fast :
    allIndexed (fastTargetCheck {N} 5 43 3 G5 G43 endpointTable) 0 rows = true := by
  apply allIndexed_of_blocks (P := fastTargetCheck {N} 5 43 3 G5 G43 endpointTable)
    (rows := rows) (b := {BLOCK}) (c := {COUNT}) (by decide) (by rw [rows_size]; decide)
  intro i
  fin_cases i
'''
    aggregate += ''.join(f'  · exact target_chunk_{i:02d}\n' for i in range(COUNT))
    aggregate += '''
theorem targets_checked :
    allIndexed (targetCheck rows.length 5 43 3 G5 G43 endpointTable) 0 rows = true := by
  simpa only [fastTargetCheck_eq, rows_size] using targets_checked_fast

end Sarkozy.OddOrder215
'''
    (ROOT / 'Sarkozy/OddOrderChecks215.lean').write_text(aggregate)
    print(f'Generated {COUNT} sequential chunks of at most {BLOCK} rows and their aggregate.')


if __name__ == '__main__':
    main()
